### ISSUE TITLE
Change Boss Mufflers Player NBT to Capabilities

### ISSUE THREAD

**Issue by vadis365** [vadis365/Mob-Grinding-Utils#1]
The NBT method is just plain old and the events don't seem to be working as they should.
Changing the old and outdated method will make the code better.

**Comment by vadis365** [comment]
Awesome fixy by @TheCyberBrick

**Comment by TheCyberBrick** [comment]
![pc8jf5t4ewcdkcmu](https://cloud.githubusercontent.com/assets/2338519/20075212/9d305e22-a533-11e6-86ae-a4aad7ce2364.jpg)
