### ISSUE TITLE
Remove sword swoosh sound from fake player

### ISSUE THREAD

**Issue by vadis365** [vadis365/Mob-Grinding-Utils#10]
never noticed it before but apparently it is local to players and follows them around globally or some shit.

**Comment by vadis365** [comment]
Sound is moved to correct location of the block - but the sound cancelling event that is added is still not doing what it should. Will leave this issue open for now as a reminder.

**Comment by vadis365** [comment]
hax wins - moved fake player to -100 Y for shits and giggles

**Comment by TheCyberBrick** [comment]
"fixed" 😄
