### ISSUE TITLE
Mob Masher losing it's inventory

### ISSUE THREAD

**Issue by realblaupilz** [vadis365/Mob-Grinding-Utils#101]
Well.. it seems like in MobGrindingUtils-0.3.7, when unloading the chunks the mob masher loses all of the upgrades I put into. Playing Foolcraft 1.4.5 btw. 

I don't think it's because of running some resturbed spawner with vindicators in it (emeralds + projecte's philosopher's stone = such OP at the beginning) :D 
![2018-08-23_01 41 16](https://user-images.githubusercontent.com/30379226/44497355-206bf600-a679-11e8-90ac-07e0dd110081.png)
![2018-08-23_01 41 20](https://user-images.githubusercontent.com/30379226/44497361-28c43100-a679-11e8-96a4-dc510945289f.png)
![2018-08-23_01 44 21](https://user-images.githubusercontent.com/30379226/44497365-2bbf2180-a679-11e8-972e-cd7e6b28187f.png)

**Comment by vadis365** [comment]
Hello,
How was the mob masher being powered? There was an issue with EnderIO conduits reported a while back - I would suggest just powering them with vanilla redstone in any build for that version but it is an old release (at the time of writing 0.3.11 is the released version of the mod) - not much I can do to help you I'm afraid, it is up to the foolcraft chaps to update there pack with more up to date versions on their next release cycle.
Cheers,
Me.

**Comment by realblaupilz** [comment]
Thanks for the reply and it's indeed connected with redstone conduits to make it much easier to wire up.
Didn't know about any issue so far ^^"
