### ISSUE TITLE
Unable to set Absorption Hopper Output

### ISSUE THREAD

**Issue by Master-Jynx** [vadis365/Mob-Grinding-Utils#105]
I'm playing Sky Factory 3.0.15 which uses Mob Grinding Utils 0.1.8.22.
I was using a Absorption Hopper until I picked it up with a Timker's pick axe.
I stored it in a chest for a while, and when i placed down at a different location,
i was unable to set the output sides.
The clicking sound would be played, nothing happened. and no error messages were given.

**Comment by vadis365** [comment]
I have no idea why this would happen, unfortunately that version is a little out of date and no longer updated. I would just cheat another one in and pretend it never happened ;)
