### ISSUE TITLE
[Question] Mob Masher / General

### ISSUE THREAD

**Issue by HurtsAsHell** [vadis365/Mob-Grinding-Utils#110]
Is there a way to increase the maximum number of upgrades?
_In case it's a duplicate, do not be bad with me ahahah_

**Comment by vadis365** [comment]
Hello,
There isn't atm, but I'm not saying I wont add it in the future.
The is actually no configs for the mod due to it being fairly simple - I'll add some at some point and consider some different options such as your request.
Cheers,
Me.

**Comment by HurtsAsHell** [comment]
okay, thanks for the answer, goodbye.
