### ISSUE TITLE
Mob Masher - Sharpness upgrades not altering/increasing damage done

### ISSUE THREAD

**Issue by MCdonut** [vadis365/Mob-Grinding-Utils#111]
When adding sharpness upgrades to the Mob Masher block, there is no increase in damage. Regardless of the number upgrades, damage done is exactly 5 hearts/10 damage. This was tested with the StoneBlock modpack (1.0.32) with Mob Grinding Utils 0.3.12. Looting appears to be working insofar as 10 upgrades of Looting seems to noticeably increase the number of drops compared to none.

**Comment by vadis365** [comment]
Hello,
Pushed 0.3.13 update to curse (awaiting approval) - should have this issue fixed - thanks for the report.
Cheers,
Me.
