### ISSUE TITLE
Easy infinite exp

### ISSUE THREAD

**Issue by Xetaxheb** [vadis365/Mob-Grinding-Utils#113]
MC 1.12.2 / MobGrindingUtils-0.3.6.jar (Forever Stranded: Lost Souls pack)
A bit outdated so sorry if this is already fixed, didn't see an issue posted. 

Putting an xp tap on the side of a singularity tank, piping 1 mb of exp into it, lets you withdraw 1 xp which is worth more to put back in. Combine this with a vacuum hopper and you'll fill tanks fairly easily. Just need a few exp to jumpstart the operation initially.

I'm using Cyclic "fluid extraction cable" but I'd imagine this can be replicated with other flow-controlled pipes. (note if you try to replicate this, that cyclic pipe tends to reset its setting on world/chunk load)

---
My test setup is just "xp tap <> tank <> cable <> tank+vac". 
This can be chained repeatedly so actually in my case it's 6 taps+tanks hooked to one tank hooked to one tank+vac. Gains a level every couple seconds and sustains itself with no input. I have a performance mod that teleports exp to nearest players and therefore it works at any distance instead of just piling up, but any kind of xp orb collector block could also do this. Another vacuum hopper for instance.

**Comment by vilhalmer** [comment]
I've poked around a bit and I believe this is caused [here](https://github.com/vadis365/Mob-Grinding-Utils/blob/MC1.12/MobGrindingUtils/MobGrindingUtils/src/main/java/mob_grinding_utils/tile/TileEntityXPTap.java#L31). The tap should be checking whether the amount left in the tank at each attempt to spawn an orb would be less than 20 mB and failing to spawn any orbs if so, but instead it forces whatever is left to be equivalent to a minimum of 20 mB.

I think it should be running `drain` with the second argument set to `false` first to simulate the drain, then looking at the [returned FluidStack](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fluids/IFluidTank.java#L73) to see if it can drain 20 mB each time.

**Comment by vadis365** [comment]
Stale and outdated version now.
