### ISSUE TITLE
mob masher crash when affected by ffenchantments "Cursed Body"

### ISSUE THREAD

**Issue by INSANEMODE** [vadis365/Mob-Grinding-Utils#114]
crash log: https://paste.dimdev.org/domezoboxe.mccrash
Minecraft version: 1.12.2
modpack: stoneblock survival 1.0.32 (modified) (ffenchantments added manually)
mod version: MobGrindingUtils-0.3.13.jar 
conflicting mod: ffenchants-1.12.2-1.1.3.jar (by flashfyre)

when a minecraft:tile.mob_grinding_utils.saw (mob masher) encounters a mod with an enchantment named "Cursed Body", the server crashes.  and takes at least 5-10 restarts of the server for it to successfully restart, usually.

**Comment by vadis365** [comment]
Hello,
This is more likely whatever mod adds that effect is trying to add it to the masher. They should be checking in their code if the player is a a Fake player. If they don't then stuff like this can happen.
If you could also report to the other mod that this is happening they may be able to fix the issue.
Cheers,
Me.
