### ISSUE TITLE
Absorption Hopper Can Crash Server

### ISSUE THREAD

**Issue by Cazitron** [vadis365/Mob-Grinding-Utils#117]
In conjunction with the mod "YABBA", if you break an anti-Barrel it keeps it NBT data so if you are to break an anti-barrel that is completely full and and absorption hopper tries to pick up the anti-barrel item then the absorption hopper exceeds the amount of allocated memory designated for the hopper. Which causes a crash loop for a server and/or single-player world (Not Tested). What we had to do to fix the corruption was to use MCEdit to remove the absorption hopper. We couldn't load a back-up because there wasn't one available at that time. This bug has had it removed from a PO3 modpack but i believe a simple fix is to just add some code to the absorption that checks if the items memory exceeds that of the hopper (So that this will fix all items that can have the same effect) and thus not pick it up. Or have the hopper dynamically allocate more memory to compensate that item and then decrease the amount of memory after the item is removed.

**Comment by vadis365** [comment]
Hello,
I can't really "give the AH more memory" - lol that just isn't how things work.
I think youre issue may be connected with this on the YABBA git issues.
https://github.com/LatvianModder/YABBA/issues/102
Please report the issue to them as well.
Cheers,
Me.
