### ISSUE TITLE
Null Pointer

### ISSUE THREAD

**Issue by ReportBot9009** [vadis365/Mob-Grinding-Utils#118]
Added Apotheosis to modpack and when I built a mob grinder with mob spawners it crashes either immediately or after certain kills, of which I have no idea.

Forge 2815

https://paste.dimdev.org/sohemikite.mccrash

**Comment by Shadows-of-Fire** [comment]
You should be able to close this (Shadows-of-Fire/Apotheosis#21), was missing a `!(e instanceof FakePlayer)`

**Comment by vadis365** [comment]
Will do - I guess the' Icy something whatnot' Enchant in another MGU issue was your fault too :P
