### ISSUE TITLE
Wither Muffler doesn't hide boss bars in multiplayer

### ISSUE THREAD

**Issue by TheEssem** [vadis365/Mob-Grinding-Utils#119]
I play on a private Stoneblock 2 server with some friends using SpongeForge. I decided to build a Wither farm, so I naturally wanted to use the Wither Muffler to disable death sounds and hide the boss bar. The former function works, but the boss bar hiding function doesn't seem to work as intended. However, when I recreate the setup in singleplayer, it works perfectly.

Minecraft version: 1.12.2
Stoneblock 2 version: 1.9.0
Mob Grinding Utils version: 0.3.13
Minecraft Forge version: 14.23.5.2808

**Comment by DreiPixel** [comment]
same problem here but another pack (sky odyssey)
