### ISSUE TITLE
Absorption Hopper grabs xp way too slowly

### ISSUE THREAD

**Issue by aaronhowser1** [vadis365/Mob-Grinding-Utils#121]
![image](https://user-images.githubusercontent.com/15698722/57164254-2c3bba80-6db9-11e9-9b14-f261fcb5c59c.png)
This simple mob farm brings my client to a crawl after a couple minutes of running. The Absorption Hopper is grabbing the XP and items, but it grabs XP way too slowly. It takes several seconds per orb, even though it's being instantly piped away. Getting rid of the pipe doesn't make it faster, nor does making it output via the Hopper instead of a servo.

**Comment by BrianEdmonds** [comment]
aaronhowser1 <notifications@github.com> writes:
> The Absorption Hopper is grabbing the XP and items, but it grabs XP
> way too slowly.

I would always recommend modpacks to use Clumps, as XP entities
overwhelming the system is a common problem otherwise.

Brian.

**Comment by vadis365** [comment]
I have increased it a bit, but it's pretty limited, there is nothing stopping you from using more than one AH if things need to work quicker as the mod isn't supposed to be a super hi-tech solution and there are other mods that will work faster/better in some cases Thanks for the report.
