### ISSUE TITLE
Mob fan distance upgrades not incerasing fan distance. 

### ISSUE THREAD

**Issue by Fevix** [vadis365/Mob-Grinding-Utils#122]
![2019-05-15_18 52 32](https://user-images.githubusercontent.com/1657108/57814732-a61d5d80-7742-11e9-831d-d9b1b9ad272f.png)

This fan has 10 distance upgrades inside it and 1 vertical upgrade. I have confirmed that the visual box is indeed the range it's blowing at, even though it should be blowing much farther. 

Adding the distance upgrades individually does not change this.

**Comment by vadis365** [comment]
I just can't duplicate this no matter how I test, the only thing that stops the box is having a block infront of the fan anywhere directly infront of it. I'm going to close this I'm sorry.
