### ISSUE TITLE
[1.12.2] Mob fan spamming packets

### ISSUE THREAD

**Issue by XFactHD** [vadis365/Mob-Grinding-Utils#123]
Mob fans seem to be spamming network packets (specifically SPacketUpdateTileEntity) leading to massive ping spikes between 250 and 5000 ms. I have found this issue with the help of the packettracker command from the [Sampler](https://minecraft.curseforge.com/projects/sampler) mod.

This is an excerpt of the verbose log with 24 mob fans with distance upgrades in the players vacinity: https://gist.github.com/XFactHD/954f3bb53f0fba61fa6c850af6e074a5
This is an excerpt of the verbose log with 24 mob fans without distance upgrades in the players vacinity: https://gist.github.com/XFactHD/733246d45b56935ed1a9aa39aab6a01f

This is happening on a plain Forge server (no Sponge, Spigot, etc.)

Minecraft version: 1.12.2
Forge version: 1.12.2-14.23.5.2811
Mod version: 0.3.13

**Comment by Sherriex** [comment]
I'm wondering if anyone found a solution to this problem, I've just encountered it with massive lag spikes on the server as soon as the Mob fans were placed,

It's been happening only on my client end, other players on the servers seem uneffected(I've already tried reinstalling a fresh client)

**Comment by vadis365** [comment]
Closing because this is a very old bug report. Not sure if this is still an issue for people, if so make a new bug report, but support for 1.12.2 is probably not going to to be quick as we have moved to newer MC versions.

**Comment by wad4444** [comment]
> Not sure if this is still an issue for people

kind of an issue, yeah? would be cool if this got fixed
