### ISSUE TITLE
Glitch when using Entity Conveyors with Hoppers

### ISSUE THREAD

**Issue by Unjustifiable** [vadis365/Mob-Grinding-Utils#124]
So, I'm aware this is probably going to be a low priority issue, but when you run a line of conveyors to a vanilla hopper the items you drop on that conveyor belt doesn't drop into the hopper like one would expect. You have to place the hopper a whole block down for the item to drop into it. While this is fine and it works, it looks silly to have that huge gap between the hopper and the conveyor belt.

**Comment by vadis365** [comment]
Yeah, that is just an issue with the blocks needing to be smaller than 1 block so entity collisions work - I don't think this will be changed atm, but I will take note of it for future versions and make a better system. Thanks for the report, will close for now, but I will take note. :)
