### ISSUE TITLE
Grinder Crash

### ISSUE THREAD

**Issue by samuelap1324** [vadis365/Mob-Grinding-Utils#139]
Cyclic belts and grinder causing crash on server

https://pastebin.pl/view/ed97d047

**Comment by Lothrazar** [comment]
`c4.conarm.common.armor.modifiers.ModSticky.onLivingHurt(ModSticky.java:48)`

**Comment by vadis365** [comment]
Whatever conarm is (I presume Constructs Armour or somesutch) is trying to apply it's enchantment to a fake player (the mob masher). They should be checking for that with a simple "instanceof" exclusion for fake players. Please reoprt it to that mod.
