### ISSUE TITLE
1.16.4 port?

### ISSUE THREAD

**Issue by Narsayden** [vadis365/Mob-Grinding-Utils#142]
Hey there, big fan of the mod, i usually add it into any modpack i make

Was wondering, do you ever plan to make it available for 1.16.4?

**Comment by Flanks255** [comment]
https://github.com/vadis365/Mob-Grinding-Utils/issues/144

**Comment by Narsayden** [comment]
> https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils/files/3239494

Excellent stuff!! thankyou :D
