### ISSUE TITLE
[1.16.5] NPE Crash with Ensorcellation's Frost Rebuke enchantment

### ISSUE THREAD

**Issue by P3pp3rF1y** [vadis365/Mob-Grinding-Utils#145]
I am getting crashes in the log below that are related to Frost Rebuke enchantment. I am pretty sure that null is being passed or is result of calls called by mob grinding utils as I used a different fake player to kill mobs before in the pack and haven't had this issue.

https://pastebin.com/8GVhjrEs

Version: mob_grinding_utils-1.16.5-0.4.2

**Comment by jeremiahwinsley** [comment]
Also getting this issue. This is likely related to https://github.com/MinecraftForge/MinecraftForge/issues/6358

**Comment by Flanks255** [comment]
Should be fixed in ebc03ca
