### ISSUE TITLE
Ticking Entity Crash 

### ISSUE THREAD

**Issue by berni1212** [vadis365/Mob-Grinding-Utils#146]
Modpack All the Mods 6 
Mod Version : 1.16.5-0.4.2

https://pastebin.com/fUkVtDtk

Server log 

Mob causing it : Vindicator with Banner

**Comment by Flanks255** [comment]
Should be fixed in ebc03ca

**Comment by wolfsack** [comment]
getting the same problem, but i think it's a different cause:

Modpack Direwolf20 - i added the mod myself
Modversion: 1.16.5-0.4.2

https://pastebin.com/UPh0nm4D

**Comment by Flanks255** [comment]
Still should be fixed in next release.
