### ISSUE TITLE
Ender Inhibitor request

### ISSUE THREAD

**Issue by CloWnicide** [vadis365/Mob-Grinding-Utils#149]
Would it be possible to have this block also cancel Mutant Enderman teleports, as it currently does not.

**Comment by Flanks255** [comment]
What mod is that? I have never heard of it.
If it does not block it it means they are not using ender teleportation, as the inhibitor blocks all usages of ender teleportation, including players using ender pearls.

**Comment by CloWnicide** [comment]
It's from the Mutant Beasts mod: https://www.curseforge.com/minecraft/mc-mods/mutant-beasts

**Comment by vadis365** [comment]
Ye, not sure we can really do anything here, it looks like he doesn't use the forge teleport event code for the teleporting, so we can't really prevent it without adding a special case, for which I'd rather not. Maybe ask the authour of Mutant Beasts to subscribe to the event when his mobs teleport?
