### ISSUE TITLE
Absorption hopper crashing server[1.16.5]

### ISSUE THREAD

**Issue by rankcuekid** [vadis365/Mob-Grinding-Utils#153]
Hello, I’ve been having some issues with the absorption hopper causing a “Ticking Block Entity” error at random instances (at least seems to be random, haven’t been able to emulate the error reliably). What details and information would you need me to provide?

**Comment by Flanks255** [comment]
crash log would be nice, and mod version :)

**Comment by rankcuekid** [comment]
[crash-2021-05-05_08.27.30-server.txt](https://github.com/vadis365/Mob-Grinding-Utils/files/6446004/crash-2021-05-05_08.27.30-server.txt)

The version is 0.4.21

**Comment by Flanks255** [comment]
looks like simple storage network got into a recursion loop?
