### ISSUE TITLE
Dreadful Dirt Ignores Ignores 0 Light if Created by Partial Blocks

### ISSUE THREAD

**Issue by desagas** [vadis365/Mob-Grinding-Utils#154]
Create a box, any size. Make the top box full cobblestone, there is 0 light, the dreadful dirt works perfectly in said environment.

Now, replace top block in box with bottom cooblestone slabs, and the sky AND block light level is still calculated as 0 by Minecraft, as it should be, yet, dreadful dirt will burn and disappear, as if it is directly in the view of the sky.

On mob_grinding_utils-1.16.5-0.4.21.jar, forge 1.16.5.36.1.2, playing with ATM6S-1.0.9.

**Comment by vadis365** [comment]
Hello,
IIRC some blocks like slabs and stairs calculate light levels different and as such won't block the light.
for example Zombies will still burn under half slabs that are exposed to the sky.
I'd suggest just using a full block - I mean we have added tinted glass that blocks out light and allows you to see in to mob farms (has connected textures too). If things spawning on the roof are an issue you could always add a layer of half slabs over a full block of cobble etc.
I'm not sure much can be done about this just atm, but I'll put it on my TODO list of things to look at,
Cheers,
Me.

**Comment by desagas** [comment]
That is true, in some cases, but not this case. But, okay. Zombies do not burn under slabs. I’m not sure if that was ever a mechanic that did exist in Minecraft. Anyways, good luck with the mod, it’s still useful.

Denver Leman

On May 15, 2021, at 7:04 AM, vadis365 ***@***.***> wrote:

﻿

Hello,
IIRC some blocks like slabs and stairs calculate light levels different and as such won't block the light.
for example Zombies will still burn under half slabs that are exposed to the sky.
I'd suggest just using a full block - I mean we have added tinted glass that blocks out light and allows you to see in to mob farms (has connected textures too). If things spawning on the roof are an issue you could always add a layer of half slabs over a full block of cobble etc.
I'm not sure much can be done about this just atm, but I'll put it on my TODO list of things to look at,
Cheers,
Me.

**Comment by desagas** [comment]
F3 is used to check, and is a Minecraft mechanic. In the box described, a perfectly dark room with absolutely no light let it, but your blocks still burn. Anyways, I just wanted to let you know. If that’s intended, so be it. :)

**Comment by vadis365** [comment]
The check for burning is a combination of a light level and if the block can see the sky. I'm not doing anything special or wonky in the code and am using vanilla methods to check such things. Irrellevant of what the F3 console shows you for the light level, slabs and some block may not trigger the vanilla method for 'seeing the sky' - I can probably look in to this as I have said, but it is a minor thing for which vanilla mechanics are really what are being quizzed tbh. :)
