### ISSUE TITLE
entity spawner

### ISSUE THREAD

**Issue by bloodscon** [vadis365/Mob-Grinding-Utils#155]
Entity spawner cost to run need looking at as it is at the moment it takes 10 enderman kills to make enough xp to spawn 1 enderman and it gets worse with lower lv mods ie chickens, pigs

**Comment by kawinskimar** [comment]
@bloodscon I can't even get it to spawn anything.

**Comment by vadis365** [comment]
Hello,
The cost is there to add a little balance to an essentially infinite thing - you can easily set up a mob farm that produces hundreds of thousands of Mb's of XP fluid with a Mob Masher, Absorption Hopper and some Dreadful Dirt. The Entity Spawner is made so you can spawn 1 specific type of mob repeatedly using an egg. Dreadful dirt will spawn hostiles and Delightful dirt passives, at no more cost than making it and filling a kill box with it.
With regards to the spawning - most mobs, using this block require a solid block below and enough space. The only things that don't are water mobs, and some mobs that have no restrictions for spawning. Ghasts and Blazes 'in code' are actually GROUND type mobs, even if vanilla spawns them in the air etc.
I don't think the XP requirements are unfair, as once you have a decent mob farm set up, and all the blocks, you can effectively spawn huge amounts of mobs at only the cost of XP from another infinite XP farm.
Cheers,
Me.

**Comment by joshorvis** [comment]
Thanks for the clarification.  I had a lot of trouble getting the Entity Spawner to produce anything until I realized it needed to be sitting on a redstone block.  Now I got mobs everywhere....
