### ISSUE TITLE
[1.16.5] Problem with mob fans.

### ISSUE THREAD

**Issue by astralxite** [vadis365/Mob-Grinding-Utils#158]
![2021-05-30_23 04 38](https://user-images.githubusercontent.com/85064769/120105241-74498900-c19b-11eb-81ac-a86306432e7e.png)
Sorry I have no idea if there is a format or anything but I just ran into this and thought it would be good to share.

From what I see on my map I believe that mob fans get stuck on the edges of chunks and don't push any further past the chunk border. Width upgrades work fine, but distance ones do, up until the chunk border. I have seen some old issues from a quick search all having this problem so it's possible it was overlooked.

Or I am just an idiot... who knows... 😛 

MCVersion 1.16.5
Latest ver of mobutils.

**Comment by Flanks255** [comment]
Doesn't appear to be chunk boarders... at least i cant get it to happen...
![image](https://user-images.githubusercontent.com/32142731/120708217-ee6e5c00-c480-11eb-9421-1a509cbb142e.png)

**Comment by Amosh73** [comment]
I have a similar problem: Range upgrades work in none of my fans, regardless of their location or orientation.

**Comment by Amosh73** [comment]
In my world it depends on the y level: Above sea level they always work, below the mostly don't.

**Comment by Amosh73** [comment]
Steps to recreate:
Create World with seed 5247517343172005414, go to -9 / 28 / -92 and place fan. Distance is 1 single block.

![2021-07-17_17 34 45](https://user-images.githubusercontent.com/76697174/126042175-f2345bea-c44f-49a9-8436-7f07cc46a470.png)

**Comment by Flanks255** [comment]
looks like mojang added "cave air" and that was borking the range checks. tyvm for the info.
