### ISSUE TITLE
No Wither egg from chicken feed

### ISSUE THREAD

**Issue by danielthorr** [vadis365/Mob-Grinding-Utils#159]
I swabbed a wither and made the GM chicken feed with it, then when I fed it to a chicken and when it exploded it didn't give me a wither egg. I made sure to check the information panel on the chicken feed and it says "Contains: "minecraft:wither" 'DNA'."

I'm playing on ATM6 To The Sky if that changes anything. 

Is this expected behavior? Is there maybe a setting in a config file somewhere?

**Comment by Flanks255** [comment]
Because there is not a spawn egg for withers, I should probably not allow the swab to function 9n mobs with no egg, which will be easy since I just added an entity tag that can block the swab.
