### ISSUE TITLE
Mob Masher causes loud noise spam at world spawn

### ISSUE THREAD

**Issue by MadMooAU** [vadis365/Mob-Grinding-Utils#16]
While the Mob Masher is on, it creates a bunch of loud noise at the cords of world spawn.

Muting player sounds causes it to disappear, which leads me to believe that it is the Mob Grinder "player".

**Comment by vadis365** [comment]
Hello,
This has already been fixed and an update was released. Please update your version.
Thanks for the issue report - I hope you are enjoying the mod.
Cheers,
Me.
