### ISSUE TITLE
[1.16.5] Not working with Thermal Foundation mob spawn eggs

### ISSUE THREAD

**Issue by Slaymeister** [vadis365/Mob-Grinding-Utils#161]
Problem and repro steps
The Mob Grinding Utils spawn egg creation method (swab => feed => chicken) does not work with Thermal Foundation Spawn Eggs (Blitz, Bazalts, Blizz). When you give the chicken the DNA feed, it will explode, but an egg will not be created.

If you get a Thermal Foundation spawn egg and place it in a Mob Grinding Utilities mob spawner, nothing happens.

Expected behavior
The feed with the mob DNA information should give an egg. The egg should activate the spawner.

**Comment by Slaymeister** [comment]
I was told the TF spawn egg is not a sub class of the vanilla minecraft spawn egg. Not sure if that's related.

**Comment by Flanks255** [comment]
Indeed they dont extend `SpawnEggItem`, i will have to come up with a fallback solution for eggs that are not registered.

**Comment by Slaymeister** [comment]
It was pointed out on the Team CoFH Discord server (Thermal) where they are discussing their spawn egg implementation that "SpawnEggItem.getEgg is onlyin(CLIENT) for no good reason, which means IForgeEntity.getPickedResult is not safe to call on the server which would otherwise be the obvious solution"  

@Flanks255  Would you like to participate in this thread? It's in #tech-support channel.  Here's the link if you would like to join.  https://discord.gg/uRKrnbH

**Comment by Flanks255** [comment]
To be honest, i wasnt using either of those methods, i was accessing the static eggs array that all the eggs that extend the class get added to.
