### ISSUE TITLE
MC 1.16.5 modded - Frequent crashes near fans; Forge

### ISSUE THREAD

**Issue by ternsip** [vadis365/Mob-Grinding-Utils#167]
https://gist.github.com/ternsip/e07915629c95908f4921896cfecc35d7

**Comment by Flanks255** [comment]
the fan wasnt pushed by a piston was it?

**Comment by ternsip** [comment]
Was not. No pistons around.

**Comment by Flanks255** [comment]
Fixed in 67e3721 hopefully
