### ISSUE TITLE
Windows Defender labeling new update as a "Severe Trojan Virus"?

### ISSUE THREAD

**Issue by ViridianFire** [vadis365/Mob-Grinding-Utils#169]
Title says it all
![image](https://user-images.githubusercontent.com/84670775/130101471-977a657c-6f1e-4627-a6c0-120b9dea51c1.png)
![image](https://user-images.githubusercontent.com/84670775/130101526-dcd24a87-23bb-48c2-9069-ecece949846c.png)

**Comment by Flanks255** [comment]
False positive, windows defender has started pinging a growing number of mods with this.
[VirusTotal scan results](https://www.virustotal.com/gui/file/0263579207b8cb736d3c3b42fe54e95a5f21ad6761640d0213627b2e042c862a/detection)

Related: FabricMC/fabric#1645

**Comment by Flanks255** [comment]
Microsoft notified me today that they have cleared the problem, hopefully these false positives will clear up soon.
