### ISSUE TITLE
Spawner Changing.

### ISSUE THREAD

**Issue by TheDCPlaya** [vadis365/Mob-Grinding-Utils#17]
Hey Vadis,

i have noticed an issue when using this mods way of changing spawner types, when i use the spawn egg to change the spawner after a few spawns it defaults back to the original type.

I will understand if this is a vanilla issue, although i used mob_grinding_utils to get the egg.

Thanks 
TheDCPlaya

**Comment by vadis365** [comment]
Hello,
Yes, this seems to be happening for other mods too. I found this when searching if other people have this problem. It seems Actually Additions had the same problem a while back.
https://github.com/Ellpeck/ActuallyAdditions/issues/162
The mod author has a fix in their code specifically to address this issue - I will see about implementing a similar fix in a future update. Thanks for the report.
Cheers,
Me.
