### ISSUE TITLE
Disable mob Spawning on Dreadful Dirt, when light level is high enough (Lamps)

### ISSUE THREAD

**Issue by aronjanosch** [vadis365/Mob-Grinding-Utils#172]
AFAIK there is no option to prevent mob-spawning on dreadful dirt. Would be excellent to disable mob-spawning when the light-level is sufficient.

**Comment by Flanks255** [comment]
It already does this, light level 10 or higher blocks spawning, tho i will probably change this to be lower, maybe 5 or so, since 1.18 changes normal spawning to be 0 anyway.
