### ISSUE TITLE
Blazes don't drop items on Iron Spikes

### ISSUE THREAD

**Issue by b0bst3r** [vadis365/Mob-Grinding-Utils#18]
MobGrindingUtils-0.1.8.12 (Sky Factory 3)

Take vanilla spawner from nether and put into spike drop, blazes drop no items when killed on iron spikes.

**Comment by vadis365** [comment]
Hello,
This isn't a bug. The iron spikes are just a basic mob trap block that doesn't count as a player kill.
The way to gain player drops is to upgrade and make the 'Mob Masher'. Kills from the Mob masher count for player drops and can be upgraded and customised for specific types of mobs and enchantment types using the upgrade items in it's gui.
Cheers,
Me.

**Comment by b0bst3r** [comment]
Ahh ok thanks I did wonder if this was the case.
