### ISSUE TITLE
Mob Masher Cant Behead Blaze?

### ISSUE THREAD

**Issue by ArkavianX** [vadis365/Mob-Grinding-Utils#184]
Got a masher running cannot seem to get a single decapitation with 10 guillotine upgrades...

Blaze is spawn in overworld with a Industrial Foregoing Mob Duplicator so it is in a pokeball (mob imprisonment tool)

ATM6 To The Sky 1.16.5 
Mob Grinding Utils 0.4.28

**Comment by Flanks255** [comment]
Blaze's dont have droppable heads.
