### ISSUE TITLE
Mob Masher Crash

### ISSUE THREAD

**Issue by emihead** [vadis365/Mob-Grinding-Utils#190]
Minecraft 1.18.1
mob_grinding_utils-1.18.1-0.4.33
Forge 39.0.55

Game crashed almost immediately after I placed down a few mob mashers.

Crash report
[crash-2022-01-23_08.56.16-server.txt](https://github.com/vadis365/Mob-Grinding-Utils/files/7920630/crash-2022-01-23_08.56.16-server.txt)

This seems to be the same issue I had with Enchantment Machine - the tile entities had some trouble saving their contents, and according to another modder I got some help from with that issue, you should use the saveAdditional function and not the save one for 1.18.

**Comment by Flanks255** [comment]
upgrade the mod to 0.4.33.

**Comment by emihead** [comment]
Respectfully, I'm ON 0.4.33, which I clarified in the original issue.

**Comment by Flanks255** [comment]
the crashlog says its on 0.4.32
`java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.BlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at mob_grinding_utils.tile.TileEntityInventoryHelper.save(TileEntityInventoryHelper.java:92) ~[mob_grinding_utils-1.18.1-0.4.32.jar%23165!/:1.18.1-0.4.32] {re:classloading}
	at mob_grinding_utils.tile.TileEntitySaw.save(TileEntitySaw.java:134) ~[mob_grinding_utils-1.18.1-0.4.32.jar%23165!/:1.18.1-0.4.32] {re:classloading}`

**Comment by emihead** [comment]
okay, i just actually checked my mods folder and i apparently had both versions?? I think this is just a case of the curseforge app being incompetent, i don't know how that happened. Sorry for bothering ^^;

**Comment by Flanks255** [comment]
phew, thats a relief, i thought i was losing my mind :) @
