### ISSUE TITLE
[1.16.5] Mob Fan doesn't push down

### ISSUE THREAD

**Issue by kingchills** [vadis365/Mob-Grinding-Utils#193]
I'm not sure if this is intended but not documented, but I can't get the mob fan to push down.  I have a ghast farm and they're spawning above the killing mechanism but staying where spawned.  I thought using the fan would move them down.  

The fan will also not push a flying player down.

Pack: Oceanblock 1.11.0
MGU Versio: 0.4.30

**Comment by Flanks255** [comment]
Tested in 1.16 and 1.18, it definitely pushed ghasts and myself down, even in creative mode.
