### ISSUE TITLE
Wither Muffler does not hide boss bar if Wither is renamed by resource pack.

### ISSUE THREAD

**Issue by Jkosio23** [vadis365/Mob-Grinding-Utils#197]
Using the "Bee Wither" resource pack from Vanilla Tweaks (https://vanillatweaks.net/picker/resource-packs/ the "fun" section) The wither boss bar was not hidden when the muffler was right clicked. 
mc 1.18 
forge 39.0.88 
MGU 0.4.33

**Comment by Jkosio23** [comment]
I'm assuming it similarly doesn't work for the Ender Dragon if the LANG file renames it, seeing as taking that line out of the English translation for this resource pack resolved the issue.

**Comment by Flanks255** [comment]
Problem is, because of the way boss bars work, all we have is the translated name to go by, only thing i could do is make a list of alternate names to check.

**Comment by Jkosio23** [comment]
Would you be able to put in a wildcard to catch anything with wither in the name?

**Comment by Flanks255** [comment]
hmmm, ya that would probably work.
