### ISSUE TITLE
dreadful dirt mob farm

### ISSUE THREAD

**Issue by lordfluffermuffins** [vadis365/Mob-Grinding-Utils#198]
um is it not possible to disable dreadful dirt in the 1.16.5 atm6 sky pack with red stone lamps? i have the lamps on and above and stuff still spawns. it says level 10 or above disables it but it doesn't. the mod is on version 0.4.32

**Comment by Flanks255** [comment]
something else must be interfering with it in the pack then, because it very much does stop spawning when lit, just tested it again in 1.16 tonight.

**Comment by Flanks255** [comment]
Tested in the same modpack now as well, works fine, cannot reproduce.
