### ISSUE TITLE
Builds 0.4.31 -0.4.35 crashes on 1.18.1 when placing blocks from the mod

### ISSUE THREAD

**Issue by Luci1991** [vadis365/Mob-Grinding-Utils#199]
Absorption Hopper, Mob Masher, and other blocks crash the game every time you place them down Forge is up to date for Minecraft version
[crash-2022-04-10_21.21.25-server.txt](https://github.com/vadis365/Mob-Grinding-Utils/files/8461695/crash-2022-04-10_21.21.25-server.txt)

**Comment by Flanks255** [comment]
It looks like you might have multiple versions of the mod installed at
once, if this is on the curse launcher that can happen sometimes, I would
open the mods folder and remove any versions older then 0.4.33, that crash
was introduced in forge 39.0.45, and preemptively fixed in mgu 0.4.33

**Comment by Luci1991** [comment]
Thank you very much that worked
