### ISSUE TITLE
Mob Masher does not drop Blaze heads

### ISSUE THREAD

**Issue by Chaos2023** [vadis365/Mob-Grinding-Utils#201]
With 10 beheading upgrades the masher did not drop a single head after filling a double chest with blaze rods. Tested with another mob and the head dropped immediately (Skeleton, two kills two heads.)

**Comment by TheonlyTazz** [comment]
Tinkers 1.18 does offer blaze heads to be dropped, which wont be dropped by the mob-masher
https://github.com/SlimeKnights/TinkersConstruct/issues/4863

**Comment by Flanks255** [comment]
Fixed in 1.18.2-0.4.38
