### ISSUE TITLE
[Bug?] Dreadful Dirt Inside of Nether Fortress Located in Warped Forest Biome Only Spawns Endermen

### ISSUE THREAD

**Issue by i2smrt4u** [vadis365/Mob-Grinding-Utils#208]
Playing on FTB DW20 1.18 v1.4.1

I created a 9x9x5 mob farm with the floor centered (xz) and located (y) at the center block of a four-way intersection. If the Minecraft wiki is correct (see link and image), this should be a valid spawn location for wither skeletons and other Nether Fortress mobs. Only endermen spawn, and at a truly absurd rate. The high spawn rate lines up with the increased spawn rate expected in this biome-fortress combination, but the mobs that are spawning do not.

Not sure if this is a bug, or if I have done something wrong.

https://minecraft.fandom.com/wiki/Nether_Fortress
![image](https://user-images.githubusercontent.com/106843452/173431716-7afc3fb1-7f3a-4b17-8c82-de1de3a06afa.png)

**Comment by Flanks255** [comment]
So looks like wither skels are special, they are not spawned by the spawn table like other mobs, which is what the dirt uses, and the only mob in the spawn table for a warped forest is endermen.
