### ISSUE TITLE
Dreadful/Delightful dirt not spawning mobs in Compact Machine if player isn't in the compact machine

### ISSUE THREAD

**Issue by PieterLab** [vadis365/Mob-Grinding-Utils#209]
Hi

Playing the Direwolf20 1.18 pack on a personal dedicated server with some friends, all configs are default.

Have the overworld chunk where the compact machine is placed, as well as the compact machine dimension chunk, loaded with FTB.
Chunk loading seems to be working, as I placed a Mekanism smelter in the compact machine, and it was pushing out whatever I was giving it to smelt to/from the overworld.
Also tested the hopper by removing the Mekanism sorter connected to it, clearing the inventory, then leaving the compact machine for 5 mins, and when going back in, there's no items in the hopper or lying around the grinder, also removed the hopper completely, and there were no items lying around after leaving and entering the compact machine.

Mobs are spawning and grinder is working 100% when my character is in the compact machine, but as soon as I leave it, the mobs stop spawning.

**Comment by matfat7** [comment]
I'm having the same issue with mobs not spawning in a chunkloaded area in the overworld unless I am nearby.

**Comment by Flanks255** [comment]
This is most likely caused by random ticks not happening when a player isn't present.
The same thing would happen with crops or anything else that grows.
