### ISSUE TITLE
Delightful Dirt not spawning any mobs.

### ISSUE THREAD

**Issue by Trogdayton** [vadis365/Mob-Grinding-Utils#213]
I'm aware that it is intended for the grass and flowers to pop up and interfere from time to time, but I am both force loading the chunk, standing nearby, and have no grass or flowers currently. Still no mobs spawning. Next chunk over the dreadful dirt is working fine. I'm on Skyopolis 5, which is 1.18.2. Any ideas? Let me know what other info you need.

**Comment by Flanks255** [comment]
what biome is it in?

**Comment by Trogdayton** [comment]
I believe it just says skyopolis, but I'll check. I'm not at home right now.

**Comment by Flanks255** [comment]
it might be located in a biome that lacks passive mobs, is why i ask.

**Comment by Trogdayton** [comment]
And of course it is. Could have sworn I checked that out already, but it's in lukewarm ocean. Welp, there's my problem. Thanks! I'll close this.

**Comment by Flanks255** [comment]
i put a disclaimer about oceans on the tooltips(529dcd9) next time we push out an update.
