### ISSUE TITLE
Bug: Entity Spawner only Spawns Mobs in NW Corner

### ISSUE THREAD

**Issue by getBoolean** [vadis365/Mob-Grinding-Utils#218]
The entity spawner only attempts spawns in the lowest north west corner of the spawn area. If that area is occupied by a mob or a block, no mobs are spawned.

Mod version: 1.18.2-0.4.42
Forge: 40.1.68
Modpack: https://www.curseforge.com/minecraft/modpacks/boolean-simply-modded

**Comment by Flanks255** [comment]
Fixed in 0.4.43 for both 1.18 and 1.19

**Comment by getBoolean** [comment]
Thanks!
