### ISSUE TITLE
Delightful Dirt - Spawned grass and flowers prevent mob spawns

### ISSUE THREAD

**Issue by aronjanosch** [vadis365/Mob-Grinding-Utils#219]
Hi,

I'm playing DW20 1.18 MGU v0.4.41.
In my passive mob spawner, on delightful dirt, plants and grass are constantly growing. This prevents mob spawning, which re enables after clearing the grass.

Is this intended ?

Love your mod <3

**Comment by Flanks255** [comment]
This is an intended mechanic.
