### ISSUE TITLE
The Dirt

### ISSUE THREAD

**Issue by Soul-Rack** [vadis365/Mob-Grinding-Utils#227]
Is there a way to get the 'dreadful dirt' or 'delightful dirt'? in survival mode? If not I think it would be cool to add a way.

**Comment by Flanks255** [comment]
there is, it involved the other types of chicken feed. the "Nutritious Chicken Feed" for delightful dirt, and the cursed feed i think is the dreadful dirt, feed them to chickens, you get a special egg that creates the dirt.
