### ISSUE TITLE
Mob-Masher-Absturz

### ISSUE THREAD

**Issue by xXjojojXx** [vadis365/Mob-Grinding-Utils#228]
**Minecraft 1.18.2
mob_grinding_utils-1.18.2-0.4.46
forge-1.18.2-40.1.80**

crash-2022-10-20_19.42.59-server
https://pastebin.com/P2X6U0zm

I get the following error message in the console and the server crashes on it irregularly but the error message is always the same. could it be because of your mod?

**Comment by Flanks255** [comment]
Hard to say, that error means the server was lagged out so hard that you were effectively under 0.016 ticks per second, at that point the game just gives up unless you have java arguments to prevent that.

**Comment by xXjojojXx** [comment]
java arguments ? -Xms8g
-Xmx40G
-XX:+UseG1GC 
-Dsun.rmi.dgc.server.gcInterval=2147483646 
-XX:+UnlockExperimentalVMOptions 
-XX:G1NewSizePercent=20 
-XX:G1ReservePercent=20 
-XX:MaxGCPauseMillis=50 
-XX:G1HeapRegionSize=32M
-XX:MaxTenuringThreshold=5
-XX:ParallelGCThreads=16
