### ISSUE TITLE
Mob Grinding Utils Crashes in JEI

### ISSUE THREAD

**Issue by MemeLord32** [vadis365/Mob-Grinding-Utils#229]
When I was scrolling through the recipes, it crashed. The crash report stated something about rendering Mob Util XP Bucket.

https://pastebin.com/XqzLcyjZ

**Comment by Flanks255** [comment]
what version of mgu? the crash log is cut off at the end and is missing the mod list.

**Comment by MemeLord32** [comment]
The latest version of MGU. 0.4.46

**Comment by Flanks255** [comment]
and what version of jei? because i haven't been able to reproduce this, has it happened more then once for you? or was it a one off crash.

**Comment by MemeLord32** [comment]
I just updated jei to the latest version. I'll see if it's fixed.

**Comment by MemeLord32** [comment]
What I did was to scroll up in the jei menu until I crashed.

https://pastebin.com/81JTQ46s

**Comment by MemeLord32** [comment]
Seems to be a pproblem with another mod. I suspect it's Rubidium, or Configured, as I see them a lot in the crash report. I'll check.

**Comment by MemeLord32** [comment]
You're not gonna like what I say but after attempting, it's not a problem with any of those mods. I now have 0 inkling on as to what the problem is.
