### ISSUE TITLE
Crash on certain mob drops

### ISSUE THREAD

**Issue by JoeyJo0** [vadis365/Mob-Grinding-Utils#23]
When using the Mob Masher, sometimes the server crashes.

[crash-2017-02-16_15.28.22-server.txt](https://github.com/vadis365/Mob-Grinding-Utils/files/780541/crash-2017-02-16_15.28.22-server.txt)

**Comment by vadis365** [comment]
Closing due to duplicate of #22 - but still investigating issue - thanks.
