### ISSUE TITLE
Dreadful and delightful dirt spawns. 

### ISSUE THREAD

**Issue by WhosBeepo** [vadis365/Mob-Grinding-Utils#236]
Mob grinding utils is great but there's a big problem with it conflicting with other mods. Example: Dreadful dirt spawns every mob you have in the game (including modded ones) while this could be useful its also very bad as it breaks the farm I am trying to make due to the fact that the mod mobs have special ability's and what not including a shield, and ability to tp outside of the box even with the ender inhibitor. I would request that you make a config for the dirt spawns so users can add and remove mobs they want to be spawned with the dirt. EX: in the config there is a section with all the mobs you have loaded (base Minecraft and mods.) from there you can comment out the mobs you want. Or an easier way just make a section where users can put the mob pack name and then the mob name to remove it from spawning aka: your_seeing_dungeons:(mob name) just like the command in game to kill said mob. I feel this would be very useful and is very much needed as I need to choose between this mod or mods to add more mobs due to the bugs it causes.

**Comment by AlienXtream** [comment]
noticed this too. "Farseer" from "Alex's Mobs" that are intendet to spawn at world boarder only (and are BRUTAL) spawn in my manual farm. all i want to do is get slime 😭

**Comment by Flanks255** [comment]
We have a "entity_types" tag for this, [the empty generated one.](https://github.com/vadis365/Mob-Grinding-Utils/blob/MC1.16.5/MobGrindingUtils/MobGrindingUtils/src/generated/resources/data/mob_grinding_utils/tags/entity_types/no_spawn.json)

/data/mob_grinding_utils/tags/entity_types/no_spawn.json

**Comment by AlienXtream** [comment]
tags and datapacks are not intuitive for general minecraft users. its also not obvious that such things even exist to them. if some inclusion of the datapack could be integrated into the mod package that generates on world creation so new players to modding minecraft dont have to struggle asking this over and over and being confused. i know datapacks are awesome for modders but being that is halfway between code and config its something many people either dont know exists or are unfamiliar with. i think basic stuff that players often need intuitive access to should remain as config files and not be ditched in favour of abstract data driven stuff like this. sure, more complex stuff like overriding the specific spawn weights for certain mobs makes sense for a datapack but disabling a specific mob from ever spawning should for sure be either in configs or part of a generated datapack that has directions in the config file of where to find it (as a comment, no actual settings). im not trying to bash on developers. i understand its really useful for them to use this stuff. its just that, for people that cant/dont look through and understand code, there is no way to know such a feature exists. like, technically i can change the spawn weights of mobs and structures through datapacks, but i have NO clue how to and its not extensively documented as far as i know which makes it harder for us as end users to be aware of, let alone make use of. i dont mean any offence or hostility. im just not optimally socially aware so please do not take any offence to my words if they come across as too abrasive as that is not the intended tone :)


 on the note of mobs in spawn tables, in the case of alex's mobs farseer its likely that they have a custom system to spawn them as i dont think minecraft has any native "distance from origin" type weighting so they are likely having to have a base spawn rate globally that they then modify with some sort of custom falloff manually. as the dreadful dirt is presumably more like a mob spawner (or at least a marker for the code to target) only getting the "base" spawn weight as the relative rolls for the mob type as opposed to accelerating the vanilla spawn attempts. its (understandably) not taking into account abstract spawning rules such as that.

**Comment by Mrbysco** [comment]
![](https://media.tenor.com/iYV1ivEd9SwAAAAC/drive-kermit.gif)

**Comment by Flanks255** [comment]
Anyway, ill add the Farseer to the default tag in the next update.
