### ISSUE TITLE
[1.16.5] Add a config for blacklist for Mobswab

### ISSUE THREAD

**Issue by MathisSkate** [vadis365/Mob-Grinding-Utils#238]
Hi, is it possible to add a blacklist file to block mobswab for mobs ?

Thanks

**Comment by Flanks255** [comment]
This exists as a "entity_type" tag [Example](https://github.com/vadis365/Mob-Grinding-Utils/blob/MC1.16.5/MobGrindingUtils/MobGrindingUtils/src/generated/resources/data/mob_grinding_utils/tags/entity_types/noswab.json)

/data/mob_grinding_utils/tags/entity_types/noswab.json
