### ISSUE TITLE
entity spawner offset

### ISSUE THREAD

**Issue by Vashta** [vadis365/Mob-Grinding-Utils#239]
not sure if this is a setting i dont know about somewhere, a bug, or dev choice but the entity spawner can only be offset by like 2 blocks at most unless i add upgrades to it the offset for it and the vacuum both need an increase in these as it makes it super difficult to set up a mob grinding room if the entity spawner practically needs to be in the room id say give them both a limit of ten offset blocks so you can have the spawner and vacuum in a room beside the actual mob grinding room

**Comment by Flanks255** [comment]
This is the intended functionality yes.
