### ISSUE TITLE
Try take DNA of Pigman and appear DNA of Zombie

### ISSUE THREAD

**Issue by Lightone** [vadis365/Mob-Grinding-Utils#24]
test with MobGrindingUtils-0.1.8.16

**Comment by vadis365** [comment]
This is a known thing - I was going to wait until I update to 1.11+ as the mobs have been separated out to different entities which makes the code easier and not require custom eggs for Wither skeletons etc.
I may implement the feature and make some custom eggs and such for this version though.
Thanks for the report.
