### ISSUE TITLE
Mob Masher kills don't truly count as player kills

### ISSUE THREAD

**Issue by drysdan** [vadis365/Mob-Grinding-Utils#244]
The tooltip for the Mob Masher says "Mobs Mashed DO count as Player Kills" and for some purposes like xp they seem to, but mobs killed by the Mob Masher don't drop some 'player kill only' item drops, like gems and affix loot from Apotheosis mod, for example.

This would seem to indicate that Mobs Mashed do not, in actuality, count as Player Kills

**Comment by Flanks255** [comment]
maybe apotheosis is blocking fake player kills?

**Comment by hgiabao** [comment]
Apotheosis is intentionally blocking Fake Player Kill as they want players to grinds hours to get gems. Dumb ass design imo what what can we do.
