### ISSUE TITLE
strange farm work

### ISSUE THREAD

**Issue by MykytaKononov** [vadis365/Mob-Grinding-Utils#245]
ran into a problem. If you move away from the farm, the experience stops accumulating in the tank. I'm using ftbchanks and item transfer works as it should. However, experience is a problem. help 
i play on ATM8 modpack

**Comment by scotty9090** [comment]
Running into the same thing, except I have no mobs spawning at all (using the Dreaded Earth) once I get approx > 8 chunks away from the farm.  Farm is chunkloaded but I'm within the render/simulation distance anyway.
