### ISSUE TITLE
Mob swab didnt work in a golem to extract DNA

### ISSUE THREAD

**Issue by Tutofull** [vadis365/Mob-Grinding-Utils#250]
So i tried in our server 1.0.15 allthemods 8 pack and in singleplayer game and the mob swab dont work in a golem to extract DNA it is normal?
In the other mobs its works correctly.

**Comment by Mitchell5200** [comment]
ATM dev here, the swab for the golem, and a few other mobs has been intentionally disabled by us, this is not a mod bug.
