### ISSUE TITLE
how to Blacklist mob?

### ISSUE THREAD

**Issue by OhTanoshi** [vadis365/Mob-Grinding-Utils#251]
I see that blacklist was added for dreadful dirt but how does one do it since no configs can be found

**Comment by Flanks255** [comment]
Using entity type tags in a datapack, these are the tags available in 1.19+
[https://github.com/vadis365/Mob-Grinding-Utils/tree/MC1.19/MobGrindingUtils/MobGrindingUtils/src/generated/resources/data/mob_grinding_utils/tags/entity_types](https://github.com/vadis365/Mob-Grinding-Utils/tree/MC1.19/MobGrindingUtils/MobGrindingUtils/src/generated/resources/data/mob_grinding_utils/tags/entity_types)
