### ISSUE TITLE
Blacklist a mob from the Mob-Swab

### ISSUE THREAD

**Issue by Cornish-Kap** [vadis365/Mob-Grinding-Utils#253]
Is there anyway to stop the mobswab from working on a specific mob? A friend of mine is making a modpack and there is a mob that would break everything if you make a spawner with it. This is 1.19.2 btw

**Comment by Flanks255** [comment]
you can use a entity type tag in a datapack, see the default one in the mod for example.
[https://github.com/vadis365/Mob-Grinding-Utils/blob/MC1.19/MobGrindingUtils/MobGrindingUtils/src/generated/resources/data/mob_grinding_utils/tags/entity_types/no_swab.json](https://github.com/vadis365/Mob-Grinding-Utils/blob/MC1.19/MobGrindingUtils/MobGrindingUtils/src/generated/resources/data/mob_grinding_utils/tags/entity_types/no_swab.json)
