### ISSUE TITLE
Mob fans distance upgrades do not work

### ISSUE THREAD

**Issue by billbertking1** [vadis365/Mob-Grinding-Utils#254]
I'm running 1.19.2-0.4.49 (outdated now, playing on alpha modpack and hasn't been updated yet) and trying to make mob farm. Doesn't matter how many distance upgrades I put in, it doesn't extend the range.
![2023-07-08_09 38 23](https://github.com/vadis365/Mob-Grinding-Utils/assets/1744629/5a426e14-1b75-4a1d-92a8-64814ade3fd9)
![2023-07-08_09 38 28](https://github.com/vadis365/Mob-Grinding-Utils/assets/1744629/76cf68f9-1b48-4e24-8fd4-0473a4c1da4e)

**Comment by billbertking1** [comment]
.....it was a torch in the way......

**Comment by Flanks255** [comment]
yup, that would do it.
