### ISSUE TITLE
Fluid XP bucket not working

### ISSUE THREAD

**Issue by capasseidk** [vadis365/Mob-Grinding-Utils#255]
i used the spout from create mod doesnt work tried the experience crystal from utilitix doesnt work

**Comment by Flanks255** [comment]
What exactly are you trying to do with the spout?
or with an experience crystal from another mod?

**Comment by Flanks255** [comment]
filling the bucket by spout definitely works.
![image](https://github.com/vadis365/Mob-Grinding-Utils/assets/32142731/6fa2ec4b-4ab6-45b0-948d-c5eedd388be8)

**Comment by capasseidk** [comment]
> filling the bucket by spout definitely works. ![image](https://user-images.githubusercontent.com/32142731/254071336-6fa2ec4b-4ab6-45b0-948d-c5eedd388be8.png)

i think its a mod i installed mb its prob incompatible with it i tried it with only Mob grinding utils and utilitix and it works normally dont know which one it is though

**Comment by mateie** [comment]
For me none of it works, I tried Fluid Encapsulator, Spout and right clicking experience crystal with a bucket and its broken.
