### ISSUE TITLE
Duping of XP

### ISSUE THREAD

**Issue by Cobra1117** [vadis365/Mob-Grinding-Utils#26]
When used with Ender IO, you can dupe XP using this chain:
Singularity Tank -> XP Tap -> Ender IO XP Vacuum -> Ender IO Tank -> (repeat)

I'm guessing that Ender IO's XP Vacuum has a different liquid-xp-per-orb conversion rate than Mob Grinding Utils.

Relevant versions:
MineCraft: 1.10.2
Mob Grinding Utils: 0.1.8.16
Ender IO: 1.10.2-3.1.171

**Comment by vadis365** [comment]
Yeah, I think EnderIO has a different ratio than MGU for XP - I'll look in to it, but using MGU with itself yields no extra XP - only when other mods are involved.

**Comment by vadis365** [comment]
Fixed in 0.1.8.18 onwards (available now)
