### ISSUE TITLE
?

### ISSUE THREAD

**Issue by DONOcoding** [vadis365/Mob-Grinding-Utils#261]
Will you do an 1.20.1 version soon ?

**Comment by DONOcoding** [comment]
?

**Comment by Flanks255** [comment]
Its ported, its being tested atm, all the material changes in 1.20 are a bit screwy.

**Comment by Dreadfull0418** [comment]
May i possibly ask for a followup on this thread. I really love this mod an hope it to work on my server soon. If it isnt too much too ask ofcourse👍

**Comment by DONOcoding** [comment]
If possible, even if the mod is not 100% finished I would be ready to add it to my modpack and finish it if necessary. @Flanks255

**Comment by DONOcoding** [comment]
> May i possibly ask for a followup on this thread. I really love this mod an hope it to work on my server soon. If it isnt too much too ask ofcourse👍

its available.

**Comment by Cypher1996** [comment]
Is there not a way to get the chicken feed for the Golden Egg anymore?
