### ISSUE TITLE
Golden Egg not receivable

### ISSUE THREAD

**Issue by Cypher1996** [vadis365/Mob-Grinding-Utils#263]
Is there anything is the works of getting the Nutricious Chicken Feed to get the Golden Chicken Egg in 1.20.1 version?

**Comment by Flanks255** [comment]
Its available the same way it always has been, for some reason the recipe just isnt showing up in JEI, sometimes... 
![image](https://github.com/vadis365/Mob-Grinding-Utils/assets/32142731/dcd5a4e2-1490-4eb9-9d28-56cfdac134fe)
