### ISSUE TITLE
Mob Masher crashing server using 1.20.1-1.0.3

### ISSUE THREAD

**Issue by Systamatic** [vadis365/Mob-Grinding-Utils#266]
I'm using a pack called SanctumNetwork, doesn't matter weather I'm in multiplayer or single player either way the game crashes (Server included)

[crash-2022-01-23_08.56.16-server.txt](https://github.com/vadis365/Mob-Grinding-Utils/files/13246723/crash-2022-01-23_08.56.16-server.txt)

**Comment by Systamatic** [comment]
I have immediately found the cause which of course happens right after making a bug report, the mod [SimpleEnchantments](https://www.curseforge.com/minecraft/mc-mods/simple-enchantments) causes the issue, though I do not know how to fix it

**Comment by Flanks255** [comment]
You have piqued my interest lol, mainly because somehow you attached a crash report from #190 from january of last year lol.
Id love to see the crash report from this crash, i could help identify the problem.

**Comment by Systamatic** [comment]
Oh that's actually really weird, I actually have no idea how I managed to attach that crash report?
Hopefully this file works, for now I just removed the Simple Enchantments mod from my mods folder and it hasn't crashed once.

[crash-2023-11-03_15.34.15-server.txt](https://github.com/vadis365/Mob-Grinding-Utils/files/13255696/crash-2023-11-03_15.34.15-server.txt)

**Comment by Flanks255** [comment]
Its hard to say, because simple enchantments is closed source, so i cant look at its code, but my guess would be its not properly handling fake players, which the masher uses to kill things.
very strange is the trace passes through command code too, code that's invoked when you use a slash command (/tp etc).

It also seems to be a MCreator mod.
