### ISSUE TITLE
Mob Masher Crashes Server When Hitting Any Entity

### ISSUE THREAD

**Issue by Bright1337** [vadis365/Mob-Grinding-Utils#267]
I'm on a 1.20.1 modpack "Sanctum Network" and just as the title says the mobmasher just crashes the server whenever hitting an entity.

[crash-2023-11-12_12.25.41-server.txt](https://github.com/vadis365/Mob-Grinding-Utils/files/13328783/crash-2023-11-12_12.25.41-server.txt)

**Comment by Flanks255** [comment]
looks like the mod Simple Enchantments is not handling fake players correctly.
It appears to be a MCreator based mod, and is firing off slash commands to do things, and is trying to do it in the context of MGU's fake player.
