### ISSUE TITLE
Unable to locate config file

### ISSUE THREAD

**Issue by Gunner76th** [vadis365/Mob-Grinding-Utils#27]
I am trying to locate the config file for Mob Grinding Utils, but I cannot seem to find one. I am needing to disable the Mob Fans in favor of a different type of mob movement. Is the config stored in a location other than the config folder, or under a name other than mobgrindingutils.cfg?

**Comment by vadis365** [comment]
Hello,
There is no config file for MGU - it has never needed one as the blocks and items don't really need it.
If you want to disable anything I would suggest using minetweaker/crafttweaker or JEI/NEI to remove the items and recipes you don't require - although, you could just not use the fans if you don't want them - I'm not adding a config to remove specific items - either use them or don't ;)
Cheers,
Me.
