### ISSUE TITLE
Masher wont do damage

### ISSUE THREAD

**Issue by ronangamero** [vadis365/Mob-Grinding-Utils#276]
I'm playing on a ATM9 server, and the masher doesnt do damage inside claims. How do I trust the fakeplayer to enable damage inside claims?

**Comment by Flanks255** [comment]
depends on the chunk claiming mod being used, but pre 1.20.4 the fakeplayer is just called mobgrindingutils or something, 1.20.4+ it uses a fake player cloning the person who placed it, fixing this problem mostly.
