### ISSUE TITLE
Delightful Dirt Turnning into Grass Block

### ISSUE THREAD

**Issue by desagas** [vadis365/Mob-Grinding-Utils#280]
I have never seen this happen before, but, in FTB Skies Expert, the Delightful dirt isn't just spawning grass on top of it, it is actually changing its own block to a grass block. Is this intended? Because it is not documented anywhere that I can find.

1.19.2, latest version as of this post.

For context, there is no direct view of the sky, It is covered by solid opaque blocks, and has two additional blocks on either side of the cover, which is 4 blocks above the Delightful dirt.

Also, while in my screenshot, I have it moving back and forth with pistons at intervals to remove the grass that bonemeals, even if I do not move it, it still results in changing to grass blocks. Also, it only happens with Delightful Dirt that has full air blocks above it, while ones that have say upper half slabs above it do not change, but, of course, those do not spawn mobs anyways.

So, with glass sides, this means that the block has 12 skylight, but no direct view of the sky. And, it happens both in the daytime and at nighttime.

![2024-02-29_10 21 57](https://github.com/vadis365/Mob-Grinding-Utils/assets/8404632/8546b234-d3e2-4c98-9f94-7988f49e5e03)

**Comment by TheonlyTazz** [comment]
This isn't Mob Grinding Utils Fault, this has been added by FTB. 
there is a 5% chance per animal spawn to turn the underlying delightful dirt back to regular grass
