### ISSUE TITLE
Allow setting XP tap fluid consumption per fluid (for compatibility)

### ISSUE THREAD

**Issue by LelouBil** [vadis365/Mob-Grinding-Utils#281]
The XP tap works with any fluid that is tagged EXPERIENCE, however some mods have other ways to convert experience into/from their fluid, and if it doesn't match Mob Grinding Util's values it will result in either infinite XP or disappearing XP.

I am asking for a way, for either mod pack makers or other mod developers, to configure the amount of fluid per XP orb for specific XP fluids.

**Comment by Flanks255** [comment]
which mod has a problematic conversion rate?
all mods i know of with liquid xp fluids use 1xp / 20mb

**Comment by LelouBil** [comment]
Create Enchantment Industry 
https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry

If you do a "loop" with their XP drain and Mob Grinding Util's XP tap you loose XP.

**Comment by Flanks255** [comment]
what is their xp drain called? im poking around in the source and have not found it yet.

**Comment by LelouBil** [comment]
It's the "disenchanter" it also absorbs the XP of any player standing on it

**Comment by LelouBil** [comment]
Here is the relevant part https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry/blob/483394f8fca730edecf990b83a23d2989515013a/src/main/java/plus/dragons/createenchantmentindustry/content/contraptions/enchanting/disenchanter/DisenchanterBlockEntity.java#L208

It seems to use the XP value of the orb as the mb amount to generate

**Comment by Flanks255** [comment]
What modpack is this in?
CreateEnchantmentIndustry does not tag its fluid as experience, so someone else is tagging it.

**Comment by LelouBil** [comment]
I was using this modpack https://www.curseforge.com/minecraft/modpacks/ragnamod-vii
