### ISSUE TITLE
Warden Dissappears in Mob Grinder

### ISSUE THREAD

**Issue by tollmann123** [vadis365/Mob-Grinding-Utils#282]
Hey i´ve build a mob farm with spawners and it was working perfectly until now, until i put the warden spawnegg into the spawner. they spawn as usual get pulled into the grinder and then suddenly dissappear without dying and without dropping their loot, while other mob drops drop as usual.

**Comment by tollmann123** [comment]
I have also now found out, that all mobs which stand infront ob the mob grinder for more than a second dissappear, so it just affects the warden cuz it takes longer to kill him, how can i fix that?

**Comment by Flanks255** [comment]
i just tried it with 2 wardens and it killed them just fine, it took like, 2 minutes but lol 
![image](https://github.com/vadis365/Mob-Grinding-Utils/assets/32142731/19b0d8c3-58f7-4a56-ae01-8571136a0c87)

**Comment by tollmann123** [comment]
i found out why it happened! in the back of the farm i had installed a mob slaughter factory from another mod, which happened to despawn all the mobs

**Comment by tollmann123** [comment]
fixed it!
