### ISSUE TITLE
Mob masher dont damage the iron golems

### ISSUE THREAD

**Issue by WallyGMS** [vadis365/Mob-Grinding-Utils#288]
I got an iron golem farm but the mob masher didnt do any damage to the golems.

**Comment by Flanks255** [comment]
It should, do you have a redstone signal to it to activate it? 
![image](https://github.com/vadis365/Mob-Grinding-Utils/assets/32142731/58ac156d-ef4c-41d1-8a31-980ac3d70cbf)

**Comment by WallyGMS** [comment]
TY!

Maybe was some issue with another mod.

**Comment by WallyGMS** [comment]
TY! maybe was some issue with another mod.
