### ISSUE TITLE
Named monster GM chicken feed

### ISSUE THREAD

**Issue by KaseiFR** [vadis365/Mob-Grinding-Utils#29]
Hi,

I could not feed chickens the GM chicken feed in multiplayer, so I tested it in single player and here's the result:
I managed to get some witch eggs by making some chickens explode, but when I named my lab witch and took its DNA, the DNA seeds no longer produced any egg. The chickens did continue to explode though.

I could not feed a chicken with either the named or unamed GM feed, but that's probably a serverside issue.

I'm using FTB Beyond 1.1.0 (MGU 0.1.8.16)

**Comment by vadis365** [comment]
Named mobs among other mobs like variants are not currently supported - will be added in a future version.

**Comment by PotatoSauceVFX** [comment]
A player on my server just tried feeding a non-named chicken and nothing happens. We are using FTB Beyond 1.6.1 (MC 1.10.2)
Mod version: 0.1.8.17

We are also using spongeforge. Has anyone else had this issue without sponge?
