### ISSUE TITLE
can't craft cursed chicken feed

### ISSUE THREAD

**Issue by minimushii** [vadis365/Mob-Grinding-Utils#293]
Hey, so I've been using MGU for quite a while and had no issues, until I tried to craft the cursed chicken feed to get the dreaded dirt. I've already crafted it twice, but for some reason now it's not letting me? I've used JEI to make sure the recipe and order is right and it moves over to the crafting table correctly, but there's no item for me to pick up? Idk what to do, every other item crafts like normal. Is there a limit or something? Thank you if you can help :)

![image](https://github.com/vadis365/Mob-Grinding-Utils/assets/172191689/315b3b87-38e0-4941-bc50-5f75ee5d9954)
![image](https://github.com/vadis365/Mob-Grinding-Utils/assets/172191689/abe66ce9-feca-44ed-94b1-d5945d869a17)

**Comment by Flanks255** [comment]
Hm, what version is this? is it in a modpack? etc.
The recipe seems to be missing buckets of experience.
It should look like this 
![image](https://github.com/vadis365/Mob-Grinding-Utils/assets/32142731/eab03943-4de8-4d78-a2aa-59de3e6affa5)

**Comment by minimushii** [comment]
omg i forgot about them lol thank you!

and yes im using a modpack, an edited version of Better MC4 v26, and the mod is 1.20.1, 1.1.0. i haven't updated the modpack in a while so could it be another mod I recently added or should I just get a different version of mgu or jei?

**Comment by Flanks255** [comment]
does it work if you put the buckets in yourself? if so that means its a JEI plugin problem, if it doesnt... then its a recipe problem.

**Comment by minimushii** [comment]
sorry i forgot to update, it worked after I unistalled and reinstalled the modpack so it could've been either of them or maybe the game just broke idk. but thank u!
