### ISSUE TITLE
[Help] How to prevent a mob from spawning on dirt

### ISSUE THREAD

**Issue by adamk33n3r** [vadis365/Mob-Grinding-Utils#296]
I found that there is a no_spawn.json and reference to creating a datapack for it, but I admit I am completely unfamiliar with how datapacks work, I'm used to config files.
I created a datapack in `world/datapacks` as `block_spawn`, with `data/mob_grinding_utils/tags/entity_types/no_spawn.json` containing the following. But this mob is still spawning. What am I doing wrong? Please help!
```
  1 {
  2   "values": [
  3     "enlightened_end:void_leviathan"
  4   ]
  5 }
```

**Comment by Flanks255** [comment]
no_spawn is for the spawner, use no_dreadful_spawn, assuming thats a hostile mob.

**Comment by adamk33n3r** [comment]
Oh! Ok. I didn't see any reference to a `no_dreadful_spawn`. Thanks!

**Comment by adamk33n3r** [comment]
As you can see in the debug screen here, I have the tag applied. But it still being spawned on dreadful dirt. If it matters, I'm on `1.20.1-1.0.3`
![image](https://github.com/user-attachments/assets/ddd0d799-42b3-4040-bb43-68019f4da9a0)

**Comment by Flanks255** [comment]
in 1.0.3 the tag is "no_dirt_spawn", in 1.1.0 it was split into the dreadful and delightful variants.
