### ISSUE TITLE
Recipe ID for the Absorption Hopper typo:

### ISSUE THREAD

**Issue by Blackalf14** [vadis365/Mob-Grinding-Utils#298]
The recipe ID for the Absorption Hopper is: 'mob_grinding_utils:recipe_absorbtion_hopper' where absorption is misspelled as shown below.

![image](https://github.com/user-attachments/assets/054a2f6c-4b06-4a27-9355-38a752f289e7)

I know it's not a big deal but still a typo I wanted to report for pack devs 👍

**Comment by Flanks255** [comment]
fixed in 1.1.5+1.21.1
