### ISSUE TITLE
need update 

### ISSUE THREAD

**Issue by captainkirk7752** [vadis365/Mob-Grinding-Utils#300]
are you going to update to 1.21 on neoforge love your mod and need it in my new world

**Comment by penturt** [comment]
Waiting on the same, would love a 1.21 neoforge version... but that's the case on a lot of mods.

**Comment by Flanks255** [comment]
working on it lol, its a big mod, and 1.21 is full of annoying changes :P

**Comment by penturt** [comment]
oh i understand, i'm just happy the mod community has adopted neoforge as fast as it has.
