### ISSUE TITLE
[1.21.1.1.0] Dreadful dirt not spawing any mob 

### ISSUE THREAD

**Issue by EnErGyBuZz04** [vadis365/Mob-Grinding-Utils#301]
modpack: [https://www.curseforge.com/minecraft/modpacks/project-architect-2](url)

After removing all the light, I placed the rotten eggs and only spawn the mobs at first time, once they die they no longer spawn

![2024-09-10_19 57 00](https://github.com/user-attachments/assets/d1dc61db-f284-4590-a9fb-e0c3c70b8bbc)

**Comment by jinkhya** [comment]
Hello
Found this issue after looking for a 1.21 report on this. Project Architect 2 is mc 1.20.1 :)
 I dunno if it's broken in 1.20.1, however I can confirm it is in 1.21 in ATM10.
 Best regards,
 Jin

**Comment by NithinV404** [comment]
Yes, this is happening in my world too the dreadful dirt is not spawning any mobs in the Direwolf20 1.21 pack

**Comment by Flanks255** [comment]
Maybe another mod is messing with random ticks? because it definitely works...

**Comment by EnErGyBuZz04** [comment]
I solved it by removing a forgotten megatorch.
Thanks to all!!

**Comment by jinkhya** [comment]
Megatorch didn't use to block those afaik?

**Comment by NithinV404** [comment]
> Megatorch didn't use to block those afaik?

Ya even I remember it as not blocking the mobs spawning

**Comment by Flanks255** [comment]
megatorch hooks the spawn event, and cancels it.

**Comment by jinkhya** [comment]
Something must have changed somewhere though, either on mega torch mod side or this mod. You used to be able to have a mega torch in your base and also use the dreadful dirt. If that no longer works you need to setup your mob farm out of range of the torch, which is fine i guess, just less convenient.

**Comment by Flanks255** [comment]
Ah yes, looks like the old "NaturalSpawner.isSpawnPositionOk" was removed, and the suggested replacement is the event, which torchmaster is hooking...

**Comment by Flanks255** [comment]
Ok, ill attempt to stop megatorches from blocking this in 1.21, this shouldnt be the case in 1.20, because its not using the event, unless the megatorches are blocking it some other way i dont know of...
