### ISSUE TITLE
Spawner crash - Zombie, Zombified Piglin, Drowned type

### ISSUE THREAD

**Issue by littlertom** [vadis365/Mob-Grinding-Utils#303]
Hi,

I know this is experimental but just providing a bug issue. Thanks again for this incredible mod.

Running build f8b1cf7.

Issue: crashing to desktop when running a spawner with specified mobs only. 

Reproduced by using mob spawner with zombie, zombie piglin or drowned and mob masher or possibly without.
Spawner had various different upgrades.

Issue stops when mobs aren't spawning.

Using all the mods modpack 1.21.1.

[2024-09-23-2.log](https://github.com/user-attachments/files/17093374/2024-09-23-2.log)

**Comment by Flanks255** [comment]
removed this event anyway as it didn't work after all, moved it to a mixin.
