### ISSUE TITLE
Absorption hopper output

### ISSUE THREAD

**Issue by jeridan** [vadis365/Mob-Grinding-Utils#32]
FTBBeyond-1.5.1-1.10.2
MobGrindingUtils-0.1.8.16

The abosorption hopper no longer outputs to a storage drawer or storage drawer controller from mod Storage Drawers.  Possibly a result of the Storage Drawer update to 3.7.1 removing legacy support that won't function with mods that haven't implemented IitemHandler?

**Comment by vadis365** [comment]
Hello,
The Absorption Hopper was updated to use the item capabilities system quite a while back and has been working up until this point with other mods fine. I'll take a look and run some tests.

https://github.com/vadis365/Mob-Grinding-Utils/blob/master/MobGrindingUtils/MobGrindingUtils/src/main/java/mob_grinding_utils/tile/TileEntityAbsorptionHopper.java#L369

Cheers,
Me.

**Comment by jeridan** [comment]
Thanks, I was just reading recent changes in the mods to offer something besides "it dont werk" except I guess it turned out to be that anyway.  I have also noticed that the absorbtion hopper won't output xp to the ender tank or items to the ExtraUtils trashcan.

**Comment by SolaKun** [comment]
+1 same issue here

**Comment by jeridan** [comment]
After some testing it appears that the absorption hopper will output xp to an endertank but only through the top of the tank.  Won't output to the trashcan in any setup I tried.

**Comment by vadis365** [comment]
Hello,
The Absorption Hopper has been updated now to deal with the slight issue of me missing some important things out when adding the inventory handling code - I wasn't actually checking for capabilities even though the code was there - doh! With regards to the Ender Tank I have no idea really as using the Singularity Tank from this mod the Absorption Hopper will fill it on any side with no issues. If things are still not working for you, you could always add translocators or conduits between the the AH and whatever storage device you are using. Let me know if the 1.8.17 version works better for you.
Cheers,
Me.

**Comment by jeridan** [comment]
Updated to version 1.8.17 and it appears to be fixed.  Thank you!
