### ISSUE TITLE
Feature Request: hopper tweaks

### ISSUE THREAD

**Issue by chibois** [vadis365/Mob-Grinding-Utils#34]
Would it be possible to have a 4th directional option to output both items and exp into the same direction for use with enderio conduits?

also would it be possible to shrink the hitbox for the hopper to the size of the hopper to make it easier to get to blocks around it?

not sure if changing the hitbox would solve this issue but it would be nice to be able to build around it with chisels and bits to either hide it or make it look like a giant eyeball...

**Comment by vadis365** [comment]
Hello,
EnderIO can already extract from the absorption hopper using their conduits - just set them to extract mode and they will pull from the hopper without any need to use the hoppers functionality for pushing out items and fluid. I'm not sure about changing the hitbox, I know it's not ideal, but it would be quite time consuming making several size changes to it depending on the output sides - hence why I opted for the easier option of making it a normal sized cube. I'll see what I can do in the future :)
Cheers,
Me.

**Comment by chibois** [comment]
diddnt realize enderio conduits would override where the pipe comes out of... *goes to try*

you could just have the hitbox smaller and you walk thru where the outputs jut out. i cant think of any reason why id need to click on specifically the output when trying to get to the hopper inventory, also have no idea how it all works if thats a possibility or not. (just reminded of how the extra heads dont count when hitting the wither, only its body and center head count.)

**Comment by vadis365** [comment]
Going to leave this for now as the shift click function for changing the sides without using the gui uses the sides. Will revisit in a future update no doubt.
