### ISSUE TITLE
Non-vanilla spawn eggs

### ISSUE THREAD

**Issue by zerofall** [vadis365/Mob-Grinding-Utils#35]
The spawn egg mechanic only works for vanilla spawn eggs. I think it has to do with this in ChickenFuseEvent.java:

`if (EntityList.ENTITY_EGGS.containsKey(name)) {`

If the logic could be tweaked to allow any modded spawn eggs, that would be awesome.

**Comment by vadis365** [comment]
Hello,
The logic does allow non-vanilla spawn eggs. Spawn eggs from my own mods work.
I think this may just be a case of certain mods not registering their eggs the same.
I will look in to updating some of the logic in the future but closing for now.
Thanks.
