### ISSUE TITLE
Rotating mob fan with wrench cause destorying containg upgrades.(Ender IO yeta wrench)

### ISSUE THREAD

**Issue by ZZaphodd** [vadis365/Mob-Grinding-Utils#36]
Probably not a mob grinding utils problem.

mob_griding_utils version : 0.1.8.16
Ender IO version : 1.10.2-3.1.179

FTB Invasion modpack version : 1.0.4

**Comment by TheCyberBrick** [comment]
@vadis365 Overriding TileEntity#shouldRefresh to only refresh when the block changes should fix this. I'll do it myself if I have time
