### ISSUE TITLE
Experience duplication 

### ISSUE THREAD

**Issue by ZZaphodd** [vadis365/Mob-Grinding-Utils#37]
Probably not a mob_grinding_utils problem
Experience rod(from ender io) shift right click on singularity tank -> XP tap -> Player got more experience before

mob_griding_utils version : 0.1.8.16
Ender IO version : 1.10.2-3.1.179

FTB Invasion modpack version : 1.0.4

**Comment by ZZaphodd** [comment]
Might be same issue or relate to this issue(https://github.com/vadis365/Mob-Grinding-Utils/issues/26), I made a separate issue just in case.

**Comment by vadis365** [comment]
Hello,
This was fixed in the latest version 0.1.8.18 - I would suggest updating.
Thanks for reporting it :)
Cheers,
Me.
