### ISSUE TITLE
Mob masher not inflicting damage

### ISSUE THREAD

**Issue by amagawd** [vadis365/Mob-Grinding-Utils#39]
I am running a Foolcraft server and the mob masher currently doesn't inflict any damage to any mobs. It seems to work fine offline but I can't seem to figure out what is causing it to not function on the server.

**Comment by vadis365** [comment]
Hello,
I'm not sure. There is the same issue with the 'Levels' mod that levels up tools.
The mob masher uses a Fake Player with an actual sword where I add and remove the upgrades - I would suggest that another mod that may effect weapons or tools may be causing the issue.
Sorry I can't be of much help with this - but it's a place to start if you need to de-bug the mod interactions.
Cheers,
Me.

**Comment by amagawd** [comment]
Found the issue, using: /gamerule doDaylightCycle false, causes the mashers to not do any damage.

David Loranger

On May 18, 2017, at 2:01 PM, vadis365 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I'm not sure. There is the same issue with the 'Levels' mod that levels up tools.
The mob masher uses a Fake Player with an actual sword where I add and remove the upgrades - I would suggest that another mod that may effect weapons or tools may be causing the issue.
Sorry I can't be of much help with this - but it's a place to start if you need to de-bug the mod interactions.
Cheers,
Me.

**Comment by vadis365** [comment]
Hello,
I think I have solved the issue - it's a derp on my behalf.
I'm using the wrong world time checking (other devs reminded me about this and I forgot to fix it) - whoops. I'll see about getting an update out and fixing this for future versions but it's not a game breaking issue for now. Thanks for the report - I'll leave this open until it's fixed just as a reminder :)
Cheers,
Me.

**Comment by Joshwoo70** [comment]
bug still affects 1.10 i have created a Pull Request to fix it.

**Comment by mGodinho87** [comment]
I've download the last version of the mod for minecraft 1.18.2 and offline it works, when I go to the server it doesn't work, can you help me to solve this problem
