### ISSUE TITLE
Texture resolution

### ISSUE THREAD

**Issue by ternsip** [vadis365/Mob-Grinding-Utils#40]
Your mod very beatiful and amazing. I use it with pleasure.
The only one inconvenience is high-resolution textures that makes mod looks mauveton along with other mods.
Please, make block/items textures 16x16 as vanilla minecraft.

**Comment by vadis365** [comment]
Hello,
I understand you may not like the higher resolution textures but I personally think some of the stuff just wouldn't be possible to do 16x16 and convey the same animatons and information.
I originally had 16x16 textures for some things but they no longer exist.
If you feel that the mod doesn't fit with your world, you could always change the textures and use a resource pack to 'downgrade' them to 16x16.
Cheers,
Me.
