### ISSUE TITLE
Right clicking an exp tank crashes the game

### ISSUE THREAD

**Issue by Mach12** [vadis365/Mob-Grinding-Utils#41]
Latest recommended Forge as I write this
Latest version of the mod
The rest is in the title
[Crash log right here](https://github.com/vadis365/Mob-Grinding-Utils/files/1033496/crash-2017-05-27_12.56.15-client.txt)

**Comment by vadis365** [comment]
Hello,
Ah, looks like I missed something that changed in the 1.11.2 code and am returning a null itemstack - that is now not how things are handled - the 1.10.2 version would be fine - it looks like I'll have to push out a fix for this ASAP - thanks for the report.
Cheers,
Me.

**Comment by TheCyberBrick** [comment]
@vadis365 I'm pretty sure it's due to a different version of Forge being used, because it's complaining that the method net.minecraftforge.fluids.FluidUtil.interactWithFluidHandler is missing

**Comment by vadis365** [comment]
Updating to a later forge indeed fixes this issue - so closing
