### ISSUE TITLE
Will this mod update to 1.12

### ISSUE THREAD

**Issue by Aareon** [vadis365/Mob-Grinding-Utils#42]
Sorry to bother you, but I have a server right now for a bunch of coders and they apparently refuse to use any Minecraft version below latest. I was just wondering if this mod had plans to update to 1.12 after Forge release?

**Comment by Kashdeya** [comment]
nope it will forever be



























































































ALONE

HAHAHAHAHAHAHAHA

**Comment by vadis365** [comment]
In reply to the original question - yeah, it will update when I have time and things move over to 1.12.
It's a bit early to be requesting an update and this is the place for issues about bugs - not updates.
