### ISSUE TITLE
Hopper interaction

### ISSUE THREAD

**Issue by ChaoticLogic** [vadis365/Mob-Grinding-Utils#43]
While the singularity tank is being fixed, I tried seeing how the mob masher would interact with hoppers and hopper minecarts. The result was surprising!  While neither was able to catch the mob drops... both the hopper and the hopper minecart would suck the upgrades out of the mob masher.

I was fairly amused after killing a few chickens and found just the masher upgrades in my hopper. XD

**Comment by BrianEdmonds** [comment]
In my experience, don't put hoppers under the mob grinder, put them in
front of the block under it, and you'll be fine.  At least that worked
fine when I was playing SF3.
