### ISSUE TITLE
[suggestion] redstone signal for tap

### ISSUE THREAD

**Issue by Terpo** [vadis365/Mob-Grinding-Utils#47]
It woulld be really helpful if the XP Tap would react to redstone signals. Yesterday I nearly crashed everything because I forgot to close the tap. And you 512 buckets in orbs can be quite a lot.^^

Playing on 1.11.2

**Comment by vadis365** [comment]
Hello,
Yeah, I could do that I guess - one day. But to be honest you forgetting to turn the tap off isn't really the mods fault :P. If you were desperate for some way of redstone activating the tap so it turns off with a pressure plate or something, I guess a block activator thing like a mechanical user or autonomous activator or any one of the many blocks that do that sort of thing could be used.
Thanks for the suggestion - I hope you are enjoying the mod :)
Cheers,
Me.
