### ISSUE TITLE
Mob Masher causes tons of FPS lag

### ISSUE THREAD

**Issue by TheUnderTaker11** [vadis365/Mob-Grinding-Utils#48]
I was surprised at just how laggy the mob masher is. I went out to an empty space in the end and placed 9 of them down in a 3x3 facing upward, and it tanked my fps down to a solid 20-30 from the 60+ it was. Putting them down near my actual base would make the game unplayable while looking at them.
EDIT: Also feel I should add they were all off when the FPS tanking happened. No animation or anything happening.

**Comment by vadis365** [comment]
Hello,
This is something that may or may not be specific to you or it may be your PC just can't handle the truth. It could be that the stars are aligned in a certain way or even a direct or indirect environmental factor causing it. An under sea volcano may have erupted, the jet stream may have changed direction by a fraction of a percent or maybe on Mount Everest a Yeti calls out across a valley causing an avalanche. Maybe I coded it to specifically do this one thing only when the chosen one was found - it's difficult to tell with such a small data set which of these things may have caused your problem. I'm pretty sure from the information you have supplied to me I can deduce which version and what other mods you are using - I'll have to check my pine cones and sea weed just to be sure that I have everything I need to perform the magic ritual that will fix everything for you - with next to no effort.
Thanks for the report - I'll certainly look in to the issue and get back to you.
Cheers,
Me.

**Comment by TheUnderTaker11** [comment]
Damn it I'm kicking myself right now. I could of at least gave the actual Minecraft version...   
I became the thing I hate, a person who reports a bug but gives no real usable information about said bug.   
MC 1.10.2   
MobGrindingUtils-0.1.8.21     
GTX 960M graphics card and 12 gigs of RAM laptop which I doubt will be very helpful specs but still.
I have tried with and without optifine and without it the fps goes from just over 30 down to about 19. The only reason I reported this in the first place and didn't just assume it was my computer is I don't see why those blocks would cause so much lag. I've seen some pretty complex models that don't come close to tanking my FPS that much by just placing 9 of them. I was stupid and didn't try placing them apart from each other cause it could be them touching causing the lag possibly. I'll try that later though.

**Comment by vadis365** [comment]
Hello,
Thanks, I'll look in to it - I've not had any issues with the block reported but I'll see if there is anything that may possibly cause any sort of FPS issues.
Cheers,
Me.

**Comment by TheUnderTaker11** [comment]
Did just test, and having them apart is about the same amount of drop. But thanks, if nothing is found just go ahead and close this, just thought I would bring it to your attention.

**Comment by vadis365** [comment]
Hello,
Hmmmm... I just placed about 60 Mob Mashers down in a test world and dropped 3FPS on a very old spec PC. I'm not entirely sure what the issue could be here. I only had 2 gig dedicated and admittedly it wasn't on fancy graphics, but I had my FPS set to 50 and it dropped to 47FPS. Dropping 3FPS (probably 5 or so randomly) isn't really much of an issue for that amount of Tile Entities - I mean you would never probably have 60 mob mashers.
I'll keep this issue open for now - but I can't seem to replicate the issue.
Cheers,
Me.

**Comment by vadis365** [comment]
![2017-07-13_00 08 39](https://user-images.githubusercontent.com/6518708/28143990-d722ca62-6760-11e7-88d4-e4769959b991.png)

as you can see - a potato rig isn't having the issue.

**Comment by TheUnderTaker11** [comment]
Huh... that's weird then, its probably some super obscure computer specific thing, or some other mod causing it. Yea I'll leave it up to you if you wanna close it or just leave it open and see if someone else has the problem.

**Comment by vadis365** [comment]
I'll close for now - but definitely keep an eye on things - thanks for bringing this to my attention.

**Comment by PantACRO4life** [comment]
yo @vadis365 1.20.1, this is happening, let me know what you need to reopen the issue.
