### ISSUE TITLE
Can't craft a Mob fan

### ISSUE THREAD

**Issue by Kranioceros** [vadis365/Mob-Grinding-Utils#49]
Hello! First of all I'd like to say I'm loving this mod so far. The issue I have is that I'm not able to craft a Mob fan on a Forge server of mine. All the other recipes seem to work though, which I find very strange. I took a screenshot where you can see the problem:

![problema-mob-grinding](https://user-images.githubusercontent.com/29001707/28243506-d699fdec-69a2-11e7-9abc-39901998f5b1.png)

I'm running a Minecraft 1.12 Forge server (14.21.1.2387) and the 0.3.2 version of the mod. The OS is Linux x64 and I'm using OpenJDK 8. I hoped you could reproduce this error and maybe fix it.

Thanks for the mod and keep up the good work!

**Comment by vadis365** [comment]
Hello,
It looks like I may have derped on the recipe and used stone slabs and not stone brick slabs (ah well).
I'll change it back in the next update, but for now, you should just be able to use the stone slabs in the recipe instead. Sorry about the confusion, the recipes had to all be re-written for 1.12.
Cheers,
Dave.

**Comment by Kranioceros** [comment]
Thanks, you are right! I used stone slabs and the problem is solved. Now I'll be able to ditch these water channels :D.

Cheers!
