### ISSUE TITLE
Singularity tanks don't share inventories? (1.11.2)

### ISSUE THREAD

**Issue by Branjoman** [vadis365/Mob-Grinding-Utils#51]
Just found out that when you put singularity tanks next to eachother, they don't join up and share inventories, making large XP stores nigh impossible to achieve without a snake of pipes. Maybe an oversight in design?

**Comment by vadis365** [comment]
Hello,
It was never intended for the tanks to attach but maybe a future feature - closing for now.
Cheers,
Me.
