### ISSUE TITLE
[1.10.2/1.11.2] XP Dupe

### ISSUE THREAD

**Issue by WTFNoNamesLeftoO** [vadis365/Mob-Grinding-Utils#54]
If you place a XP Tap on a XP Drain Singularity Tank, turn it on and stand on top of the drain, you will receive more xp than the you are draining. That means you are generating experience, which obviously shouldn't happen. Please have a look into that. Cheers.

**Comment by orionSquared** [comment]
Utilizing the 1.11.2 version, I'm also experiencing this bug.

**Comment by vadis365** [comment]
Hello,
I have tested this over and over again and can't duplicate what people are telling me - but I'm not saying it doesn't happen ;) - the xp calculations for MC are a overly complex for what they do and converting to and from a fluid will make it moreso - I'll look in to this and see if this long standing thing can be addressed (not sure if it still happens in 1.12 as I have changes a few things).
Cheers,
Me.
