### ISSUE TITLE
[Request] Default-style textures

### ISSUE THREAD

**Issue by WTFNoNamesLeftoO** [vadis365/Mob-Grinding-Utils#55]
Since the mod uses a different resolution than the original 16x16 for its textures, I offer you to help you  out with those. I will attach a mockup later when I get the chance. I understand that not everyone (including me) is an artist, but a mod's visuals play a huge role in how a mod feels.

**Comment by vadis365** [comment]
Hello,
The textures are intended to be higher than 16x16.
Feel free to make your own resources as MC allows for you to add any textures you like.
Cheers,
Me.
