### ISSUE TITLE
Absorption Hopper no longer distributing items? (1.11.2)

### ISSUE THREAD

**Issue by animationdork** [vadis365/Mob-Grinding-Utils#57]
I have no idea what happened, but I had set up a hostile mob farm when I noticed that none of the items the absorption hopper collected were being distributed into the chest anymore, even though I set the correct port to that. They're just sitting in the absorption hopper. The XP fluid is the only thing getting sent away into the tanks. The mob masher doesn't seem to work anymore either, nor the fans; mobs are just standing on top of the mashers and fans don't seem to be pushing any of them, even when they're running.

I was playing around with a bunch of command codes for a while, but I don't know if they have any effect on mods?

I'm currently playing on 1.11.2

**Comment by vadis365** [comment]
sorry - I have no idea what you did to make it not work - lol
