### ISSUE TITLE
Mob egg on spawner only works for one spawn

### ISSUE THREAD

**Issue by cstdenis** [vadis365/Mob-Grinding-Utils#58]
I changed a blaze spawner to an enderman spawner with an enderman egg from gm chicken feed. It spawned a single enderman, then changed back to a blaze spawner.

**Comment by vadis365** [comment]
Hello,
This is a vanilla bug that is well known - I could probably fix it in my mod, but maybe vanilla will do it before me.
Cheers,
Me.
