### ISSUE TITLE
1.12.2 Mob spawner revert back to original mob type after 1 spawn

### ISSUE THREAD

**Issue by LordHellscream** [vadis365/Mob-Grinding-Utils#62]
i got an enderman egg from the chicken, then used on a skeleton spawner, it turns that into an enderman spawner, however after just 1 spawn of ender it reverts back to skeleton spawner.
is this a bug?

**Comment by BrisingrAerowing** [comment]
That's just how it works in survival mode. You need to be in Creative to permanently change a spawner's type.

**Comment by maxell45146** [comment]
A slight work around is to use a Drop of Evil from ExtUtil2. If you use the drop on the newly changed spawner 'before' the first spawn it will lock in the mob type when the spawner is changed to a resturbed mob spawner. Was able to do this with villagers when I was looking for a Cartographer.

**Comment by jmcaffee** [comment]
This is happening to me in my Direwolf20 1.12 world. 

Using a wither skelly spawn egg created with a swab, I change a blaze spawner (in the nether) to a wither skelly spawner with the egg, then use the drop of evil to get a resturbed spawner. On placing the spawner, it says its a wither spawner, spawns one wither skelly then starts spawning blazes. Breaking and replacing the spawner results in it saying it's a blaze spawner.

See [Actually Additions issue 162](https://github.com/Ellpeck/ActuallyAdditions/issues/162) comments by @greymerk for potential solutions.

**Comment by vadis365** [comment]
Other mods have better ways of making mob spawners - I may change this in the future but it is a low priority thing right now. Closing for now - but will reference this issue if I change the code to add this function. - Thanks.
