### ISSUE TITLE
Feature/Behavior change request with Vacuum Hoppers

### ISSUE THREAD

**Issue by Nightcaste** [vadis365/Mob-Grinding-Utils#66]
I've discovered that the vacuum hopper can be set to directly output into a pipe, which is awesome.

I've also discovered that if the vacuum hopper is set to directly output into a pipe, it's not one-directional. Items in the pipe can go into the hopper and jam it up or create a loop, which is not awesome.

I would like to ask that there either be a UI option to disable piping items into the vacuum hopper.

**Comment by vadis365** [comment]
Hello,
I think that is more an issue with you piping network than the mod itself, being able to pipe in to a VH is just a by-product of other mods interaction which I left enabled. I could stop that from happening but would probably get more complaints, so I'll consider, like you said, about a UI button. Thanks for the suggestion.
Cheers,
Me.

**Comment by kolhed** [comment]
Another suggestion is a range DOWNgrade for the hopper... 
It have a surprising range sometimes, and it anyway sits within a few blocks of the masher

**Comment by Nightcaste** [comment]
That's a unrelated issue that should go in a different thread.

**Comment by kolhed** [comment]
not so much of an issue as a suggestion to the same block, but I see your point :)

**Comment by vadis365** [comment]
Old version - time to close this.
