### ISSUE TITLE
Masher = fake player ?

### ISSUE THREAD

**Issue by Thyriel** [vadis365/Mob-Grinding-Utils#68]
Hi,

can it be that the masher acts as a fake player ?
Just noticed when i add drops with LootTweaker that can only drop when a mob is killed by a player that these drops also drop when killed by a mesher (which isn't good)

**Comment by vadis365** [comment]
Hello,
That is the whole point of using the Mob Masher in the 1st place - it acts as a fake player and gets you drops that a player would also drop. Unfortunately the mod works in that way and would have to be totally re-coded for it to do what you need. The Iron Spikes in the mod are however not fake players and only drop the things mobs would do without player interaction + XP. Sorry about that - but it's just the way the mod works.
Cheers,
Me.

**Comment by Thyriel** [comment]
Maybe you could somewhen change it so it's either configurable or only a fake player with an upgrade ?

**Comment by Kashdeya** [comment]
if you think it is so cheap for a mob farm then install craft tweaker and change the recipe. That is a lot better then asking a mod dev to completely change their mod just because you think something is OP.

**Comment by Darkosto** [comment]
I think the recipe and the way the block is setup is absolutely fine. If the recipe is an issue then I would follow Kashdeya's advice and change the recipe to your own needs. Your situation and opinion is not indicative of the entire community. 

As a modpack developer, you have the tools to alter this block in the way you need.
