### ISSUE TITLE
Fan causing massive lags

### ISSUE THREAD

**Issue by LemADEC** [vadis365/Mob-Grinding-Utils#69]
As of 0.3.4, fans can be spammed around with no restrictions nor consequence for players while killing the server TPS.
Please consider changing the implementation or gameplay around those blocks as we can't keep them enabled on public servers 'as is'.

**Comment by vadis365** [comment]
Hello,
The Fan code hasn't changed since the original implementation so it's strange this issue has cropped up now. I've not had any reports of this before, I'll take a look at the code but don't think there is much I'll be able to do for your TPS issue.
Cheers,
Me.

**Comment by vadis365** [comment]
Closing for now as I don't see a fix for this being implemented to stop player's placing loads of blocks - use less blocks and add upgrades to make them more efficient I guess.

**Comment by LemADEC** [comment]
We can't really count on player to reduce the number of fans, so we'll have to disable them for the time being.

**Comment by morrissimo** [comment]
FWIW: facing the same issue on our server - been looking for another solution to the massive TPS sink that these fans are for some reason, but we're out of options: having to ban/disable them :( 

A [sponge timings sampling](https://timings.aikar.co/?id=358582388bac4779b5334a0172b579b4) that highlights the performance bottleneck. At first glance it appears that the lag is the result of an interaction between the fan TileEntity's behavior and [GriefPrevention's](https://github.com/MinecraftPortCentral/GriefPrevention) entity collision code.

* FTB Revelation 1.5.0
* forge-1.12.2-14.23.2.2613
* spongeforge-1.12.2-2611-7.1.0-BETA-2970
* griefprevention-1.12.2-4.3.0.567

@LemADEC - are you using sponge (or spigot, etc) on your server?

**Comment by LemADEC** [comment]
Sponge has no relation with the issue at hand.
Effect should be computed per entity instead of per fans times per entity. This could be achieved by caching the cumulated fan effect per block or using belts instead of fans.
