### ISSUE TITLE
mystical agriculture support idea

### ISSUE THREAD

**Issue by Tenchu98** [vadis365/Mob-Grinding-Utils#71]
Chunk dagger based spikes that are crafted using soularium and 3 chunk daggers. Increase chance of chunk(higher pecent) and inferium(small amount) drops.

**Comment by Tenchu98** [comment]
I know it is adding support for another mod, which most modders dont like doing a specific mod, but it is more of a starting point for further expansion.

**Comment by vadis365** [comment]
Maybe ask BlakeBro about this on his github issues for Mystical Agriculture. He's a friendly chap and loves to add extra features to all his mods.
