### ISSUE TITLE
Absorption Hopper Question

### ISSUE THREAD

**Issue by Iskall86** [vadis365/Mob-Grinding-Utils#73]
On Curseforge it is not clear to if the absorption hopper is able to suck items through walls. Am playing Project Ozone Lite 1.3.6 (so no “Just use the Advanced Item Collector!!!”).

**Comment by vadis365** [comment]
Yes. It uses a radius and any item in that radius is absorbed. No sucking through walls as such - but walls do not inhibit it's ability.
