### ISSUE TITLE
Mob Swab & Chicken feed only work for vanilla mobs

### ISSUE THREAD

**Issue by Froggy800** [vadis365/Mob-Grinding-Utils#74]
GM chicken feed crafted with a Mob Swab used on a non-vanilla mob does nothing but kill the chicken it's used on, without it dropping the Spawn Egg.
I guess it's because unlike Spawn Eggs, the Mob Swab doesn't save the mod ID in the nbt field, so the process cannot successfully craft an egg.
Tested on version 0.3.4 on Forge 14.23.1.2606

**Comment by vadis365** [comment]
Hello,
This should all work now  in 0.3.5 - Let me know if it's fixed for you.
Cheers,
Me.

**Comment by Froggy800** [comment]
Nope, still not working. The chicken explodes as expected but still doesn't drop a mob egg.
I can confirm that this happens because the mod ID isn't saved in the swab/chicken feed: using a mob swab on a pink slime returns an item with the mguMobName tag that only contains "pink_slime", so I used the command _`/give [player] mob_grinding_utils:mob_swab 1 1 {mguMobName: "industrialforegoing:pink_slime"}`_ and the GM feed crafted from it worked correctly.
Thank you.
