### ISSUE TITLE
Mob Ooze Crashes on server

### ISSUE THREAD

**Issue by DarkMatterXCIX** [vadis365/Mob-Grinding-Utils#75]
anytime i put down mob ooze and it tries to spawn something it crashes server
https://pastebin.com/EmVT2VVY

**Comment by Kashdeya** [comment]
From the looks of it that is a mylittlemobgrinder crash but I could be wrong. I am sure Vadis will correct me if I am.

**Comment by vadis365** [comment]
Hello,
That crash isn't related or caused by this mod. I think Kashdeya is correct in his detective work.
Please report to the mob author.
Cheers,
Dave.
