### ISSUE TITLE
Singularity Tank Request

### ISSUE THREAD

**Issue by TookUrSweetRoll** [vadis365/Mob-Grinding-Utils#76]
Can you add a config to increase the capacity, or an upgraded tank that holds more? I take the drain tank and tap with me to mend my gear when travelling or mining.

**Comment by BigAl607** [comment]
It would also be nice if placing singularity tanks next to each other would allow them to merge into one large tank, with the ability to ad the xp drain tank to fill all the tanks, Kind of like the old EU tanks did.
