### ISSUE TITLE
Modpack with Technic Launcher

### ISSUE THREAD

**Issue by Goju-Sulfam** [vadis365/Mob-Grinding-Utils#78]
I am currently making a modpack on the Technic Launcher for a small community and i want to include "Mob Grinding Utils" into it, but to do that i need to pack it with the other in a zip file (I don't plan to use the Solder system).

Can i get your authorization to do that ?

Using the curse/twitch launcher is not an option because it doesn't have a linux version currently.

**Comment by vadis365** [comment]
Hello,
I'd rather not have the mod re-distributed through any other platform than the twitch launcher. Unfortunately some other sites are not as thorough in their user security for malware and virus checks.
Cheers,
Me.
