### ISSUE TITLE
Mob Masher not mashing Galacticraft Evolved Creepers

### ISSUE THREAD

**Issue by DerpityDoo** [vadis365/Mob-Grinding-Utils#81]
Not sure where the problem lies with this mod interaction, thought I should also post it here. 

Link to original post: https://github.com/Darkosto/SevTech-Ages/issues/2035

**Comment by justinrusso** [comment]
Hey @vadis365, any idea on this issue?

**Comment by vadis365** [comment]
Not really got a answer to this tbh. The Mob masher requires mobs to actually collide with it from it's facing side to work (I think), the mobs in the picture are next to it not 'under it'.
I'll take a look at changing the masher - it's a little limited in range. Closing but noted as a need to improve the collision - ty.
