### ISSUE TITLE
[1.10.2] Distance Upgrades not making any affect on the fans distance

### ISSUE THREAD

**Issue by MJRLegends** [vadis365/Mob-Grinding-Utils#84]
Hello, so the Distance Upgrades when put in the Mob Fan dont seem to affect the range in which the fan blows

Im not sure if your still updating the MC 1.10.2 but feel free to close the issue

This issue was report to me over at: https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/243

Mob-Grinding-Utils Version: MobGrindingUtils-0.1.8.22

MJRLegends

**Comment by vadis365** [comment]
closing due to no reply from MJR about this.
