### ISSUE TITLE
Crash on initialization

### ISSUE THREAD

**Issue by Dragnier** [vadis365/Mob-Grinding-Utils#86]
Crashlog: https://paste.dimdev.org/kacuxodami.mccrash

**Comment by vadis365** [comment]
No idea - never seen that before - looks like something weird went wrong on your loading.
Does this happen every time or was it just a one off thing?

**Comment by Dragnier** [comment]
Actually, this was an error with another mod but I forgot to come close this. Sorry for the inconvenience.
