### ISSUE TITLE
Block entity being ticked minecraft:tile.mob_grinding_utils.saw Sevtech 3.0.8 server.

### ISSUE THREAD

**Issue by dodgythoughts** [vadis365/Mob-Grinding-Utils#87]
this block keeps causing the server to crash, have had to remove it from users bases.

[crash-2018-06-18_05.01.56-server.txt](https://github.com/vadis365/Mob-Grinding-Utils/files/2112622/crash-2018-06-18_05.01.56-server.txt)

**Comment by vadis365** [comment]
Hello,
Whatever mod add traits to armour maybe causing problems and may not be checking for attacks from fake players - it could be that.
at c4.conarm.common.armor.traits.TraitVengeful.onHurt(TraitVengeful.java:58)
Cheers,
Me.

**Comment by vadis365** [comment]
https://github.com/TheIllusiveC4/ConstructsArmory/issues/63
