### ISSUE TITLE
Server crashes when a player is hit by the MobGrinder.

### ISSUE THREAD

**Issue by freaki2010** [vadis365/Mob-Grinding-Utils#89]
The problem is described very simply.
If a player is hit by the MobGrinder, the server crashes. CrashReport is attached.
https://pastebin.com/N0XvkYGN

**Comment by vadis365** [comment]
at com.unitedworldminers.CoreIO.events.EventBus.onEntityAttack(EventBus.java:172)

Whatever mod this is may not me checking for a fake player entity in their event.
Please report to the author of that mod as well.
Cheers,
Me.

**Comment by vadis365** [comment]
https://git.unitedworldminers.com/io/BaseIO/commit/0cebdcd06521f7effb6c09493fb5f8fa576b1c96

looks like they fixed their mod now.
