### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by CritFlaw** [vadis365/Mob-Grinding-Utils#92]
The client crashes while I assume rendering the new updated version of the mod

https://hastebin.com/cixahofoci.sql

**Comment by tedmihu** [comment]
Just noticed that log is blank, this one is not https://hastebin.com/kohikewuca.sql

Also, we are on version 2708 of Forge and 0.3.7 of Mob Grinding Utils

**Comment by TheSnowyChickens** [comment]
Same crash here. :)

**Comment by vadis365** [comment]
I have now changed the way the code works - it has been tested on a dedicated server and placed and broken in all states with no problems. Closing as 0.3.8 'should' now have this sorted.
