### ISSUE TITLE
Mufflers Not Functioning on Dedicated Servers

### ISSUE THREAD

**Issue by SnowShock35** [vadis365/Mob-Grinding-Utils#93]
#### Issue Details

- Minecraft 1.12.2
- Minecraft Forge 14.23.2.2618
- Mob Grinding Utils 0.3.4 (Yet to try the newer build - though from the changelog not gathered that anything to do with these blocks has changed) 

#### Issue Description

The boss bar on a dedicated server doesn't get hidden either by the person that right-clicked the wither boss muffler nor any other players

#### Issue Media

![Issue Media #1](https://ss.snowshock35.com/2018/02/1519470898-a37fa07e.png)

**Comment by vadis365** [comment]
Tested on a clean install with just MGU and JEI and the block works fine on a dedicated server . I can't replicate this problem, it may be a weird mod interaction with another mod. Closing because I just can't duplicate the bug.
