### ISSUE TITLE
Mob Mashers Seem to be Freezing Game

### ISSUE THREAD

**Issue by nightstick24** [vadis365/Mob-Grinding-Utils#94]
Hello there, I'm running the modpack FoolCraft3, which is running mob grinding utils v0.3.7 and I've run into an issue on singleplayer.

I've got a mob farm setup, using nine mob mashers to kill the mobs after they drop down from a natural spawning pad above. Seemingly randomly, mobs freeze, inventories don't open, blocks break but don't drop, and the game doesn't save. But animated blocks still move and WAILA updates.

These freezes don't fix themselves, you have to forcefully close minecraft, using task manager or something similar. After some searching, mob mashers seem to be the cause as removing them via McEdit fixes the problem every time.

You can reproduce the issue, but as mentioned it happens seemingly randomly. Sometimes I can play for a couple days without issue, other times it can happen two or three times in a day. Anyways, to reproduces just use some mob mashers to kill mobs; something happens eventually and your game will freeze up like mentioned above.

Once your game freezes due to this once, it'll freeze you every time you try to load up your world as soon as the world loads. Deleting the mob mashers via something like McEdit seems to be the only way to fix it.

There doesn't appear to be any crash log or logs relating to it, that I can find. The game just freezes it doesn't crash - but it'll stay frozen indefinitely. Every time I've had a freeze there's been mobs on the mashers getting killed.

I suspect it's something to do with loading/unloading the chunk at bad times, or saving the game at bad times, or something like that - but that's pure speculation. I'll try to pay more attention to see if there are any patterns I can notice in the future.

I've reported this over at the FoolCraft3 git too.

**Comment by vadis365** [comment]
Hello,
I have tested this on my dedicated sever and cannot replicate the issues you are having. Could be any number of reasons causing your issue and this is the only report I have had of the blocks actually freezing a player's game O.o.
If the client is still running (animations on blocks etc) then it sounds like the server is having issues.
As I have said I cannot replicate this, which leads me to think it may be a mod pack issue.
Closing as I don't have any information to go on here. If the issue persists and you have some sort of profiling log I may have more info to work with.
Cheers,
Me.
