### ISSUE TITLE
Mob Mashers don't damage mobs that are fanned up into them

### ISSUE THREAD

**Issue by Revvilo** [vadis365/Mob-Grinding-Utils#95]
Hello!
I'm on FoolCraft 3, and recently I tried to make a system where there is a fan at the bottom of a shaft with a bunch of mashers at the top, where in theory the mobs would get blown upward into the mashers creating a bit of a spectacle while gathering mob drops.

<img src="https://user-images.githubusercontent.com/13816212/42480788-5192c960-8433-11e8-9e31-107fcfba65ba.png" width="350px">

Unfortunately, it doesn't seem to damage anything at all. As far as I can tell, the only time mobs take damage is when they suffocate for a tick - or until they are dead in the case of baby zombies.
I've tried putting down multiple fans, too, but to no avail.
I understand that the Minecraft collision boxes might be a bit weird to deal with and thus making this difficult or impossible to fix, but I think it would be a cool addition to the functionality if it is fixable.

Thanks for your time!

**Comment by vadis365** [comment]
I have changed the mob masher now to work 1 pixel worth over it's block bounds - this does however mean the block now exceeds 1 block for collision. Best I can do for now and it should work for you - make sure you don't have a side exposed where you can collide with (even the base) - (0.3.8 will have this)
